// Major UK & European airports (ICAO drives the AeroDataBox lookup).
// Source: OurAirports (public domain), European countries, large airports plus
// medium airports with scheduled service. Sorted by name.

export const AIRPORTS = [
  { icao: 'LECO', iata: 'LCG', name: 'A Coruña Airport', city: 'Culleredo' },
  { icao: 'EKYT', iata: 'AAL', name: 'Aalborg Airport', city: 'Aalborg' },
  { icao: 'EKAH', iata: 'AAR', name: 'Aarhus Airport', city: 'Aarhus' },
  { icao: 'UNAA', iata: 'ABA', name: 'Abakan International Airport', city: 'Abakan' },
  { icao: 'EGPD', iata: 'ABZ', name: 'Aberdeen International Airport', city: 'Aberdeen' },
  { icao: 'LIBP', iata: 'PSR', name: 'Abruzzo Airport', city: 'Pescara' },
  { icao: 'LTAF', iata: 'ADA', name: 'Adana Şakirpaşa Airport', city: 'Seyhan' },
  { icao: 'LTBJ', iata: 'ADB', name: 'Adnan Menderes International Airport', city: 'Gaziemir' },
  { icao: 'LEMD', iata: 'MAD', name: 'Adolfo Suárez Madrid–Barajas Airport', city: 'Madrid' },
  { icao: 'LTCP', iata: 'ADF', name: 'Adıyaman Airport', city: 'Adıyaman' },
  { icao: 'LPVZ', iata: 'VSE', name: 'Aerodromo Goncalves Lobato (Viseu Airport)', city: 'Viseu' },
  { icao: 'LFKJ', iata: 'AJA', name: 'Ajaccio Napoléon Bonaparte airport', city: 'Ajaccio' },
  { icao: 'URMG', iata: 'GRV', name: 'Akhmat Kadyrov Grozny International Airport', city: 'Grozny' },
  { icao: 'LGPZ', iata: 'PVK', name: 'Aktion National Airport', city: 'Preveza' },
  { icao: 'BIAR', iata: 'AEY', name: 'Akureyri International Airport', city: 'Akureyri' },
  { icao: 'EGJA', iata: 'ACI', name: 'Alderney Airport', city: 'Saint Anne' },
  { icao: 'LGAL', iata: 'AXD', name: 'Alexandroupoli Democritus Airport', city: 'Alexandroupolis' },
  { icao: 'UNEE', iata: 'KEJ', name: 'Alexei Leonov Kemerovo International Airport', city: 'Kemerovo' },
  { icao: 'LIEA', iata: 'AHO', name: 'Alghero-Fertilia Airport', city: 'Alghero' },
  { icao: 'LEAL', iata: 'ALC', name: 'Alicante-Elche Miguel Hernández Airport', city: 'Alicante' },
  { icao: 'LEAM', iata: 'LEI', name: 'Almería Airport', city: 'Almería' },
  { icao: 'ENAT', iata: 'ALF', name: 'Alta Airport', city: 'Alta' },
  { icao: 'UOOO', iata: 'NSK', name: 'Alykel International Airport', city: 'Norilsk' },
  { icao: 'ULDD', iata: 'AMV', name: 'Amderma Airport', city: 'Amderma' },
  { icao: 'EHAM', iata: 'AMS', name: 'Amsterdam Airport Schiphol', city: 'Amsterdam' },
  { icao: 'URKA', iata: 'AAQ', name: 'Anapa Vityazevo Airport', city: 'Krasnyi Kurgan' },
  { icao: 'ENAN', iata: 'ANX', name: 'Andøya Airport, Andenes', city: 'Andenes' },
  { icao: 'LFLP', iata: 'NCY', name: 'Annecy Meythet airport', city: 'Annecy' },
  { icao: 'LTAI', iata: 'AYT', name: 'Antalya International Airport', city: 'Antalya' },
  { icao: 'EBAW', iata: 'ANR', name: 'Antwerp International Airport (Deurne)', city: 'Antwerp' },
  { icao: 'LRAR', iata: 'ARW', name: 'Arad International Airport', city: 'Arad' },
  { icao: 'ESNX', iata: 'AJR', name: 'Arvidsjaur Airport', city: 'Arvidsjaur' },
  { icao: 'URWA', iata: 'ASF', name: 'Astrakhan Narimanovo Boris M. Kustodiev International Airport', city: 'Astrakhan' },
  { icao: 'LEAS', iata: 'OVD', name: 'Asturias Airport', city: 'Ranón' },
  { icao: 'LGAV', iata: 'ATH', name: 'Athens Eleftherios Venizelos International Airport', city: 'Spata-Artemida' },
  { icao: 'LFLW', iata: 'AUR', name: 'Aurillac airport', city: 'Aurillac' },
  { icao: 'LFMV', iata: 'AVN', name: 'Avignon Caumont airport', city: 'Avignon' },
  { icao: 'LRCL', iata: 'CLJ', name: 'Avram Iancu Cluj International Airport', city: 'Cluj-Napoca' },
  { icao: 'LTCO', iata: 'AJI', name: 'Ağrı Airport', city: 'Ağrı' },
  { icao: 'LRBC', iata: 'BCM', name: 'Bacău George Enescu International  Airport', city: 'Bacău' },
  { icao: 'LEBZ', iata: 'BJZ', name: 'Badajoz Airport', city: 'Badajoz' },
  { icao: 'UIUU', iata: 'UUD', name: 'Baikal International Airport', city: 'Ulan Ude' },
  { icao: 'UWSB', iata: 'BWO', name: 'Balakovo Airport', city: 'Balakovo' },
  { icao: 'LTBF', iata: 'BZI', name: 'Balıkesir Airport', city: 'Balıkesir' },
  { icao: 'LTFD', iata: 'EDO', name: 'Balıkesir Koca Seyit Airport', city: 'Edremit' },
  { icao: 'LQBK', iata: 'BNX', name: 'Banja Luka International Airport', city: 'Mahovljani' },
  { icao: 'ENDU', iata: 'BDU', name: 'Bardufoss Airport', city: 'Målselv' },
  { icao: 'LIBD', iata: 'BRI', name: 'Bari Karol Wojtyła International Airport', city: 'Bari' },
  { icao: 'UNBB', iata: 'BAX', name: 'Barnaul Gherman Titov International Airport', city: 'Barnaul' },
  { icao: 'EGPR', iata: 'BRR', name: 'Barra Airport', city: 'Eoligarry' },
  { icao: 'LFKB', iata: 'BIA', name: 'Bastia-Poretta International airport', city: 'Bastia' },
  { icao: 'LTCJ', iata: 'BAL', name: 'Batman Airport', city: 'Batman' },
  { icao: 'LFOB', iata: 'BVA', name: 'Beauvais-Tillé airport', city: 'Beauvais' },
  { icao: 'UWKE', iata: 'NBC', name: 'Begishevo Airport', city: 'Nizhnekamsk' },
  { icao: 'EGAA', iata: 'BFS', name: 'Belfast International Airport', city: 'Belfast' },
  { icao: 'UUOB', iata: 'EGO', name: 'Belgorod International Airport', city: 'Belgorod' },
  { icao: 'LYBE', iata: 'BEG', name: 'Belgrade Nikola Tesla Airport', city: 'Belgrade' },
  { icao: 'USHQ', iata: 'EYK', name: 'Beloyarskiy Airport', city: '' },
  { icao: 'EGPL', iata: 'BEB', name: 'Benbecula Airport', city: 'Balivanich' },
  { icao: 'ENBR', iata: 'BGO', name: 'Bergen Airport, Flesland', city: 'Bergen' },
  { icao: 'LFBE', iata: 'EGC', name: 'Bergerac Dordogne-Périgord airport', city: 'Bergerac' },
  { icao: 'ENBV', iata: 'BVG', name: 'Berlevåg Airport', city: 'Berlevåg' },
  { icao: 'EDDB', iata: 'BER', name: 'Berlin Brandenburg Airport', city: 'Berlin' },
  { icao: 'LSZB', iata: 'BRN', name: 'Bern Airport', city: 'Bern' },
  { icao: 'LFBZ', iata: 'BIQ', name: 'Biarritz Pays Basque airport', city: 'Biarritz' },
  { icao: 'LEBB', iata: 'BIO', name: 'Bilbao Airport', city: 'Bilbao' },
  { icao: 'EKBI', iata: 'BLL', name: 'Billund Airport', city: 'Billund' },
  { icao: 'EGBB', iata: 'BHX', name: 'Birmingham Airport', city: 'Birmingham, West Midlands' },
  { icao: 'EDNY', iata: 'FDH', name: 'Bodensee Airport Friedrichshafen', city: 'Friedrichshafen' },
  { icao: 'ENBO', iata: 'BOO', name: 'Bodø Airport', city: 'Bodø' },
  { icao: 'LIPE', iata: 'BLQ', name: 'Bologna Guglielmo Marconi Airport', city: 'Bologna' },
  { icao: 'LIPB', iata: 'BZO', name: 'Bolzano Airport', city: 'Bolzano (BZ)' },
  { icao: 'LFBD', iata: 'BOD', name: 'Bordeaux–Mérignac Airport', city: 'Bordeaux' },
  { icao: 'EKRN', iata: 'RNN', name: 'Bornholm Airport', city: 'Rønne' },
  { icao: 'EGHH', iata: 'BOH', name: 'Bournemouth Airport', city: 'Bournemouth' },
  { icao: 'USDB', iata: 'BVJ', name: 'Bovanenkovo Airport', city: 'Bovanenkovo' },
  { icao: 'LPBG', iata: 'BGC', name: 'Bragança Airport', city: 'Bragança' },
  { icao: 'UIBB', iata: 'BTK', name: 'Bratsk Airport', city: 'Bratsk' },
  { icao: 'LDSB', iata: 'BWK', name: 'Brač Airport', city: 'Gornji Humac' },
  { icao: 'LRBV', iata: 'GHV', name: 'Brașov-Ghimbav International Airport', city: 'Brașov (Ghimbav)' },
  { icao: 'EDDW', iata: 'BRE', name: 'Bremen Airport', city: 'Bremen' },
  { icao: 'LIPO', iata: 'VBS', name: 'Brescia Gabriele d\'Annunzio Airport', city: 'Montichiari (BS)' },
  { icao: 'LFRB', iata: 'BES', name: 'Brest Bretagne airport', city: 'Brest' },
  { icao: 'UMBB', iata: 'BQT', name: 'Brest International Airport', city: 'Brest' },
  { icao: 'LIBR', iata: 'BDS', name: 'Brindisi Airport', city: 'Brindisi' },
  { icao: 'EGGD', iata: 'BRS', name: 'Bristol Airport', city: 'Bristol' },
  { icao: 'LFSL', iata: 'BVE', name: 'Brive Souillac airport', city: 'Brive' },
  { icao: 'LKTB', iata: 'BRQ', name: 'Brno-Tuřany Airport', city: 'Brno' },
  { icao: 'EBBR', iata: 'BRU', name: 'Brussels Airport', city: 'Zaventem' },
  { icao: 'EBCI', iata: 'CRL', name: 'Brussels South Charleroi Airport', city: 'Charleroi' },
  { icao: 'UUBP', iata: 'BZK', name: 'Bryansk International Airport', city: 'Bryansk' },
  { icao: 'ENBN', iata: 'BNN', name: 'Brønnøysund Airport, Brønnøy', city: 'Brønnøy' },
  { icao: 'LRBS', iata: 'BBU', name: 'Bucharest Băneasa Aurel Vlaicu International Airport', city: 'Bucharest' },
  { icao: 'LROP', iata: 'OTP', name: 'Bucharest Henri Coandă International Airport', city: 'Otopeni' },
  { icao: 'LHBP', iata: 'BUD', name: 'Budapest Liszt Ferenc International Airport', city: 'Budapest' },
  { icao: 'UWKB', iata: 'UUA', name: 'Bugulma Airport', city: 'Bugulma' },
  { icao: 'LBBG', iata: 'BOJ', name: 'Burgas Airport', city: 'Burgas' },
  { icao: 'LTBR', iata: 'YEI', name: 'Bursa Yenişehir Airport', city: 'Yenişehir' },
  { icao: 'ENBS', iata: 'BJF', name: 'Båtsfjord Airport', city: 'Båtsfjord' },
  { icao: 'LFMU', iata: 'BZR', name: 'Béziers Vias airport', city: 'Béziers' },
  { icao: 'LFRK', iata: 'CFR', name: 'Caen Carpiquet airport', city: 'Caen' },
  { icao: 'LIEE', iata: 'CAG', name: 'Cagliari Elmas Airport', city: 'Cagliari' },
  { icao: 'LFKC', iata: 'CLY', name: 'Calvi Sainte Catherine Airport', city: 'Calvi' },
  { icao: 'EGEC', iata: 'CAL', name: 'Campbeltown Airport', city: 'Campbeltown' },
  { icao: 'LFMK', iata: 'CCF', name: 'Carcassonne Salvaza Airport', city: 'Carcassonne' },
  { icao: 'EGFF', iata: 'CWL', name: 'Cardiff International Airport', city: 'Cardiff' },
  { icao: 'LPCS', iata: 'CAT', name: 'Cascais Airport', city: 'Cascais' },
  { icao: 'LECH', iata: 'CDT', name: 'Castellón-Costa Azahar Airport', city: 'Castellón de la Plana' },
  { icao: 'LFCK', iata: 'DCM', name: 'Castres Mazamet Airport', city: 'Castres' },
  { icao: 'LICC', iata: 'CTA', name: 'Catania-Fontanarossa Airport', city: 'Catania' },
  { icao: 'LFOK', iata: 'XCR', name: 'Chalons Vatry airport', city: 'Chalons en Champagne' },
  { icao: 'LFLB', iata: 'CMF', name: 'Chambéry Aix les Bains airport', city: 'Chambéry' },
  { icao: 'LGSA', iata: 'CHQ', name: 'Chania International Airport', city: 'Souda' },
  { icao: 'LFPG', iata: 'CDG', name: 'Charles de Gaulle International Airport', city: 'Paris (Roissy-en-France, Val-d\'Oise)' },
  { icao: 'UWKS', iata: 'CSY', name: 'Cheboksary Airport', city: 'Cheboksary' },
  { icao: 'ULWC', iata: 'CEE', name: 'Cherepovets Airport', city: 'Cherepovets' },
  { icao: 'UKLN', iata: 'CWC', name: 'Chernivtsi International Airport', city: 'Chernivtsi' },
  { icao: 'UESS', iata: 'CYX', name: 'Cherskiy Airport', city: 'Cherskiy' },
  { icao: 'LGHI', iata: 'JKH', name: 'Chios Island National Airport', city: 'Chios Island' },
  { icao: 'UIAA', iata: 'HTA', name: 'Chita-Kadala International Airport', city: 'Chita' },
  { icao: 'LUKK', iata: 'RMO', name: 'Chişinău International Airport', city: 'Chişinău' },
  { icao: 'UESO', iata: 'CKH', name: 'Chokurdakh Airport', city: 'Chokurdah' },
  { icao: 'UELL', iata: 'NER', name: 'Chulman Airport', city: 'Neryungri' },
  { icao: 'LIRA', iata: 'CIA', name: 'Ciampino–G. B. Pastine International Airport', city: 'Rome' },
  { icao: 'EGAE', iata: 'LDY', name: 'City of Derry Airport', city: 'Derry, Derry and Strabane' },
  { icao: 'LFLC', iata: 'CFE', name: 'Clermont-Ferrand Auvergne airport', city: 'Clermont-Ferrand' },
  { icao: 'EDDK', iata: 'CGN', name: 'Cologne Bonn Airport', city: 'Köln (Cologne)' },
  { icao: 'LICB', iata: 'CIY', name: 'Comiso Airport', city: 'Comiso' },
  { icao: 'EKCH', iata: 'CPH', name: 'Copenhagen Kastrup Airport', city: 'Copenhagen' },
  { icao: 'EKRK', iata: 'RKE', name: 'Copenhagen Roskilde Airport', city: 'Roskilde' },
  { icao: 'EPWR', iata: 'WRO', name: 'Copernicus Wrocław Airport', city: 'Wrocław' },
  { icao: 'LGKR', iata: 'CFU', name: 'Corfu Ioannis Kapodistrias International Airport', city: 'Kerkyra (Corfu)' },
  { icao: 'EICK', iata: 'ORK', name: 'Cork International Airport', city: 'Cork' },
  { icao: 'EGHQ', iata: 'NQY', name: 'Cornwall Airport Newquay', city: 'Newquay' },
  { icao: 'LRCV', iata: 'CRA', name: 'Craiova International Airport', city: 'Craiova' },
  { icao: 'LPMA', iata: 'FNC', name: 'Cristiano Ronaldo International Airport', city: 'Funchal' },
  { icao: 'LIBC', iata: 'CRV', name: 'Crotone Sant\'Anna Pythagoras Airport', city: 'Isola di Capo Rizzuto (KR)' },
  { icao: 'LIMZ', iata: 'CUF', name: 'Cuneo International Airport', city: 'Levaldigi (CN)' },
  { icao: 'GCRR', iata: 'ACE', name: 'César Manrique-Lanzarote Airport', city: 'San Bartolomé' },
  { icao: 'LEBA', iata: 'ODB', name: 'Córdoba Airport', city: 'Córdoba' },
  { icao: 'ESSD', iata: 'BLE', name: 'Dala Airport', city: 'Borlange' },
  { icao: 'LTBS', iata: 'DLM', name: 'Dalaman International Airport', city: 'Dalaman' },
  { icao: 'LFRG', iata: 'DOL', name: 'Deauville Normandie airport', city: 'Deauville' },
  { icao: 'LHDC', iata: 'DEB', name: 'Debrecen International Airport', city: 'Debrecen' },
  { icao: 'LFSD', iata: 'DIJ', name: 'Dijon Longvic airport', city: 'Dijon' },
  { icao: 'LFRD', iata: 'DNR', name: 'Dinard Pleurtuit Saint-Malo airport', city: 'Dinard' },
  { icao: 'LTCC', iata: 'DIY', name: 'Diyarbakır Airport', city: 'Diyarbakır' },
  { icao: 'UKDD', iata: 'DNK', name: 'Dnipro International Airport', city: 'Dnipro' },
  { icao: 'LFGJ', iata: 'DLE', name: 'Dole Tavaux Airport', city: 'Dole' },
  { icao: 'UUDD', iata: 'DME', name: 'Domodedovo International Airport', city: 'Moscow' },
  { icao: 'EIDL', iata: 'CFN', name: 'Donegal Airport', city: 'Donegal' },
  { icao: 'EDLW', iata: 'DTM', name: 'Dortmund Airport', city: 'Dortmund' },
  { icao: 'EDDC', iata: 'DRS', name: 'Dresden Airport', city: 'Dresden' },
  { icao: 'EIDW', iata: 'DUB', name: 'Dublin Airport', city: 'Dublin' },
  { icao: 'LDDU', iata: 'DBV', name: 'Dubrovnik Ruđer Bošković Airport', city: 'Dubrovnik' },
  { icao: 'EGPN', iata: 'DND', name: 'Dundee Airport', city: 'Dundee' },
  { icao: 'EDDL', iata: 'DUS', name: 'Düsseldorf Airport', city: 'Düsseldorf' },
  { icao: 'EGNX', iata: 'EMA', name: 'East Midlands Airport', city: 'Nottingham, Leicestershire' },
  { icao: 'EGED', iata: 'EOI', name: 'Eday Airport', city: 'Eday' },
  { icao: 'EGPH', iata: 'EDI', name: 'Edinburgh Airport', city: 'Edinburgh' },
  { icao: 'BIEG', iata: 'EGS', name: 'Egilsstaðir Airport', city: 'Egilsstaðir' },
  { icao: 'EHEH', iata: 'EIN', name: 'Eindhoven Airport', city: 'Eindhoven' },
  { icao: 'GCHI', iata: 'VDE', name: 'El Hierro Airport', city: 'El Hierro Island' },
  { icao: 'LTCA', iata: 'EZS', name: 'Elazığ Airport', city: 'Elazığ' },
  { icao: 'URWI', iata: 'ESL', name: 'Elista Airport', city: 'Elista' },
  { icao: 'ULMM', iata: 'MMK', name: 'Emperor Nicholas II Murmansk Airport', city: 'Murmansk' },
  { icao: 'EFET', iata: 'ENF', name: 'Enontekio Airport', city: 'Enontekio' },
  { icao: 'LCEN', iata: 'ECN', name: 'Ercan International Airport', city: 'Tymbou (Kirklar)' },
  { icao: 'EDDE', iata: 'ERF', name: 'Erfurt-Weimar Airport', city: 'Erfurt' },
  { icao: 'LTCD', iata: 'ERC', name: 'Erzincan Airport', city: 'Erzincan' },
  { icao: 'LTCE', iata: 'ERZ', name: 'Erzurum International Airport', city: 'Erzurum' },
  { icao: 'EKEB', iata: 'EBJ', name: 'Esbjerg Airport', city: 'Esbjerg' },
  { icao: 'LTAC', iata: 'ESB', name: 'Esenboğa International Airport', city: 'Ankara' },
  { icao: 'LFSB', iata: 'BSL', name: 'EuroAirport Basel–Mulhouse–Freiburg', city: 'Bâle / Mulhouse' },
  { icao: 'EGTE', iata: 'EXT', name: 'Exeter International Airport', city: 'Exeter, Devon' },
  { icao: 'LEGR', iata: 'GRX', name: 'F.G.L. Airport Granada-Jaén Airport', city: 'Granada' },
  { icao: 'LICJ', iata: 'PMO', name: 'Falcone–Borsellino Airport', city: 'Palermo' },
  { icao: 'LPFR', iata: 'FAO', name: 'Faro - Gago Coutinho International Airport', city: 'Faro' },
  { icao: 'LIPR', iata: 'RMI', name: 'Federico Fellini International Airport', city: 'Rimini (RN)' },
  { icao: 'LFKF', iata: 'FSC', name: 'Figari Sud-Corse Airport', city: 'Figari' },
  { icao: 'LIRQ', iata: 'FLR', name: 'Florence Airport, Peretola', city: 'Firenze (FI)' },
  { icao: 'LPFL', iata: 'FLW', name: 'Flores Airport', city: 'Santa Cruz das Flores' },
  { icao: 'ENFL', iata: 'FRO', name: 'Florø Airport', city: 'Florø' },
  { icao: 'LIBF', iata: 'FOG', name: 'Foggia Gino Lisa Airport', city: 'Foggia (FG)' },
  { icao: 'LIPK', iata: 'FRL', name: 'Forlì-Luigi Ridolfi International Airport', city: 'Forlì (FC)' },
  { icao: 'LPPR', iata: 'OPO', name: 'Francisco de Sá Carneiro Airport', city: 'Porto' },
  { icao: 'EDDF', iata: 'FRA', name: 'Frankfurt Main Airport', city: 'Frankfurt am Main' },
  { icao: 'EDFH', iata: 'HHN', name: 'Frankfurt-Hahn Airport', city: 'Frankfurt am Main (Lautzenhausen)' },
  { icao: 'GCFV', iata: 'FUE', name: 'Fuerteventura Airport', city: 'El Matorral' },
  { icao: 'UWSG', iata: 'GSV', name: 'Gagarin International Airport', city: 'Saratov' },
  { icao: 'LTAJ', iata: 'GZT', name: 'Gaziantep Oğuzeli International Airport', city: 'Gaziantep' },
  { icao: 'LTFG', iata: 'GZP', name: 'Gazipaşa-Alanya Airport', city: 'Gazipaşa' },
  { icao: 'EPGD', iata: 'GDN', name: 'Gdańsk Lech Wałęsa Airport', city: 'Gdańsk' },
  { icao: 'URKG', iata: 'GDZ', name: 'Gelendzhik Airport', city: 'Gelendzhik' },
  { icao: 'LSGG', iata: 'GVA', name: 'Geneva International Airport', city: 'Geneva' },
  { icao: 'LIMJ', iata: 'GOA', name: 'Genoa Cristoforo Colombo Airport', city: 'Genova (GE)' },
  { icao: 'EGAC', iata: 'BHD', name: 'George Best Belfast City Airport', city: 'Belfast' },
  { icao: 'LXGB', iata: 'GIB', name: 'Gibraltar Airport', city: 'Gibraltar' },
  { icao: 'LEGE', iata: 'GRO', name: 'Girona-Costa Brava Airport', city: 'Girona' },
  { icao: 'EGPF', iata: 'GLA', name: 'Glasgow Airport', city: 'Glasgow' },
  { icao: 'EGPK', iata: 'PIK', name: 'Glasgow Prestwick Airport', city: 'Prestwick, South Ayrshire' },
  { icao: 'UUDL', iata: 'IAR', name: 'Golden Ring Yaroslavl International Airport', city: 'Tunoshna' },
  { icao: 'UMGG', iata: 'GME', name: 'Gomel Airport', city: 'Gomel' },
  { icao: 'LPGR', iata: 'GRW', name: 'Graciosa Airport', city: 'Santa Cruz da Graciosa' },
  { icao: 'GCLP', iata: 'LPA', name: 'Gran Canaria Airport', city: 'Gran Canaria Island' },
  { icao: 'LOWG', iata: 'GRZ', name: 'Graz Airport', city: 'Feldkirchen bei Graz' },
  { icao: 'LFLS', iata: 'GNB', name: 'Grenoble Alpes Isère Airport', city: 'Grenoble' },
  { icao: 'EHGG', iata: 'GRQ', name: 'Groningen Airport Eelde', city: 'Groningen' },
  { icao: 'BIGR', iata: 'GRY', name: 'Grímsey Airport', city: 'Grímsey/Sandvík' },
  { icao: 'EGJB', iata: 'GCI', name: 'Guernsey Airport', city: 'Saint Peter Port' },
  { icao: 'ESNG', iata: 'GEV', name: 'Gällivare Airport', city: 'Gällivare' },
  { icao: 'ESGG', iata: 'GOT', name: 'Göteborg Landvetter Airport', city: 'Göteborg' },
  { icao: 'LTCW', iata: 'YKO', name: 'Hakkari Yüksekova Airport', city: 'Hakkari' },
  { icao: 'ESMT', iata: 'HAD', name: 'Halmstad Airport', city: 'Halmstad' },
  { icao: 'EDDH', iata: 'HAM', name: 'Hamburg Helmut Schmidt Airport', city: 'Hamburg' },
  { icao: 'ENHF', iata: 'HFT', name: 'Hammerfest Airport', city: 'Hammerfest' },
  { icao: 'EDDV', iata: 'HAJ', name: 'Hannover Airport', city: 'Hannover' },
  { icao: 'ENEV', iata: 'EVE', name: 'Harstad/Narvik Airport', city: 'Evenes' },
  { icao: 'LTBY', iata: 'AOE', name: 'Hasan Polatkan Airport', city: 'Eskişehir' },
  { icao: 'LTDA', iata: 'HTY', name: 'Hatay Airport', city: 'Antakya' },
  { icao: 'ENHD', iata: 'HAU', name: 'Haugesund Airport, Karmøy', city: 'Karmøy' },
  { icao: 'EFHK', iata: 'HEL', name: 'Helsinki Vantaa Airport', city: 'Helsinki (Vantaa)' },
  { icao: 'LGIR', iata: 'HER', name: 'Heraklion International Nikos Kazantzakis Airport', city: 'Heraklion' },
  { icao: 'EDAH', iata: 'HDF', name: 'Heringsdorf Airport', city: 'Zirchow' },
  { icao: 'ENHV', iata: 'HVG', name: 'Honningsvåg Airport, Valan', city: 'Honningsvåg' },
  { icao: 'BIHN', iata: 'HFN', name: 'Hornafjörður Airport', city: 'Höfn' },
  { icao: 'LPHR', iata: 'HOR', name: 'Horta Airport', city: 'Horta' },
  { icao: 'EGNJ', iata: 'HUY', name: 'Humberside Airport', city: 'Grimsby, Lincolnshire' },
  { icao: 'LHSM', iata: 'SOB', name: 'Hévíz–Balaton Airport', city: 'Sármellék' },
  { icao: 'LRIA', iata: 'IAS', name: 'Iaşi International Airport', city: 'Iaşi' },
  { icao: 'LEIB', iata: 'IBZ', name: 'Ibiza Airport', city: 'Ibiza (Eivissa)' },
  { icao: 'UOII', iata: 'IAA', name: 'Igarka Airport', city: 'Igarka' },
  { icao: 'EPBY', iata: 'BZG', name: 'Ignacy Jan Paderewski Bydgoszcz Airport', city: 'Bydgoszcz' },
  { icao: 'UHBB', iata: 'BQS', name: 'Ignatyevo Airport', city: 'Blagoveschensk' },
  { icao: 'LIME', iata: 'BGY', name: 'Il Caravaggio International Airport', city: 'Orio al Serio (BG)' },
  { icao: 'LOWI', iata: 'INN', name: 'Innsbruck Airport', city: 'Innsbruck' },
  { icao: 'EGPE', iata: 'INV', name: 'Inverness Airport', city: 'Inverness' },
  { icao: 'LGIO', iata: 'IOA', name: 'Ioannina King Pyrrhus National Airport', city: 'Ioannina' },
  { icao: 'EIKN', iata: 'NOC', name: 'Ireland West Airport Knock', city: 'Charlestown' },
  { icao: 'UIII', iata: 'IKT', name: 'Irkutsk International Airport', city: 'Irkutsk' },
  { icao: 'EGPI', iata: 'ILY', name: 'Islay Airport', city: 'Isle of Islay, Argyll and Bute' },
  { icao: 'EGNS', iata: 'IOM', name: 'Isle of Man Airport', city: 'Castletown' },
  { icao: 'LTFJ', iata: 'SAW', name: 'Istanbul Sabiha Gökçen International Airport', city: 'Pendik, Istanbul' },
  { icao: 'EFIV', iata: 'IVL', name: 'Ivalo Airport', city: 'Ivalo' },
  { icao: 'UKLI', iata: 'IFO', name: 'Ivano-Frankivsk International Airport', city: 'Ivano-Frankivsk' },
  { icao: 'UUBI', iata: 'IWA', name: 'Ivanovo South Airport', city: 'Ivanovo' },
  { icao: 'USII', iata: 'IJK', name: 'Izhevsk Airport', city: 'Izhevsk' },
  { icao: 'LTCT', iata: 'IGD', name: 'Iğdır Airport', city: 'Iğdır' },
  { icao: 'LTFM', iata: 'IST', name: 'İstanbul Airport', city: 'Istanbul' },
  { icao: 'LTBA', iata: 'ISL', name: 'İstanbul Atatürk Airport', city: 'Istanbul(Bakırköy)' },
  { icao: 'LEJR', iata: 'XRY', name: 'Jerez Airport', city: 'Jerez de la Frontera' },
  { icao: 'EGJJ', iata: 'JER', name: 'Jersey Airport', city: 'St. Peter' },
  { icao: 'EFJO', iata: 'JOE', name: 'Joensuu Airport', city: 'Joensuu' },
  { icao: 'LEBL', iata: 'BCN', name: 'Josep Tarradellas Barcelona-El Prat Airport', city: 'Barcelona' },
  { icao: 'LPPD', iata: 'PDL', name: 'João Paulo II Airport', city: 'Ponta Delgada' },
  { icao: 'EFJY', iata: 'JYV', name: 'Jyväskylä Airport', city: 'Jyväskylän Maalaiskunta' },
  { icao: 'ESGJ', iata: 'JKG', name: 'Jönköping Airport', city: 'Jönköping' },
  { icao: 'LTCN', iata: 'KCM', name: 'Kahramanmaraş Airport', city: 'Kahramanmaraş' },
  { icao: 'EFKI', iata: 'KAJ', name: 'Kajaani Airport', city: 'Kajaani' },
  { icao: 'LGKL', iata: 'KLX', name: 'Kalamata Airport', city: 'Kalamata' },
  { icao: 'ESMQ', iata: 'KLR', name: 'Kalmar Airport', city: 'Kalmar' },
  { icao: 'LKKV', iata: 'KLV', name: 'Karlovy Vary Airport', city: 'Karlovy Vary' },
  { icao: 'EDSB', iata: 'FKB', name: 'Karlsruhe Baden-Baden Airport', city: 'Rheinmünster' },
  { icao: 'ESOK', iata: 'KSD', name: 'Karlstad Airport', city: 'Karlstad' },
  { icao: 'LGKP', iata: 'AOK', name: 'Karpathos Airport', city: 'Karpathos Island' },
  { icao: 'LTCF', iata: 'KSY', name: 'Kars Airport', city: 'Kars' },
  { icao: 'EDVK', iata: 'KSF', name: 'Kassel Airport', city: 'Calden' },
  { icao: 'EPKT', iata: 'KTW', name: 'Katowice Wojciech Korfanty International Airport', city: 'Katowice' },
  { icao: 'EYKA', iata: 'KUN', name: 'Kaunas International Airport', city: 'Kaunas' },
  { icao: 'LGKV', iata: 'KVA', name: 'Kavala Alexander the Great International Airport', city: 'Kavala' },
  { icao: 'LTAU', iata: 'ASR', name: 'Kayseri Erkilet International Airport', city: 'Kayseri' },
  { icao: 'UWKD', iata: 'KZN', name: 'Kazan International Airport', city: 'Kazan' },
  { icao: 'LGKF', iata: 'EFL', name: 'Kefallinia Airport', city: 'Kefallinia Island' },
  { icao: 'BIKF', iata: 'KEF', name: 'Keflavik International Airport', city: 'Reykjavík' },
  { icao: 'EFKE', iata: 'KEM', name: 'Kemi-Tornio Airport', city: 'Kemi / Tornio' },
  { icao: 'UHMK', iata: 'KPW', name: 'Keperveem Airport', city: 'Keperveem' },
  { icao: 'EIKY', iata: 'KIR', name: 'Kerry Airport', city: 'Farranfore' },
  { icao: 'UHHH', iata: 'KHV', name: 'Khabarovsk Novy Airport', city: 'Khabarovsk' },
  { icao: 'USHH', iata: 'HMA', name: 'Khanty Mansiysk Airport', city: 'Khanty-Mansiysk' },
  { icao: 'UOHH', iata: 'HTG', name: 'Khatanga Airport', city: 'Khatanga' },
  { icao: 'UKOH', iata: 'KHE', name: 'Kherson International Airport', city: 'Kherson' },
  { icao: 'UMKK', iata: 'KGD', name: 'Khrabrovo Airport', city: 'Kaliningrad' },
  { icao: 'ENKR', iata: 'KKN', name: 'Kirkenes Airport, Høybuktmoen', city: 'Kirkenes' },
  { icao: 'EGPA', iata: 'KOI', name: 'Kirkwall Airport', city: 'Kirkwall, Orkney Islands' },
  { icao: 'ESNQ', iata: 'KRN', name: 'Kiruna Airport', city: 'Kiruna' },
  { icao: 'EFKT', iata: 'KTT', name: 'Kittilä International Airport', city: 'Kittilä' },
  { icao: 'LOWK', iata: 'KLU', name: 'Klagenfurt Airport', city: 'Klagenfurt am Wörthersee' },
  { icao: 'USRK', iata: 'KGP', name: 'Kogalym International Airport', city: 'Kogalym' },
  { icao: 'EFKK', iata: 'KOK', name: 'Kokkola-Pietarsaari Airport', city: 'Kokkola / Kruunupyy' },
  { icao: 'USSS', iata: 'SVX', name: 'Koltsovo Airport', city: 'Yekaterinburg' },
  { icao: 'UHKK', iata: 'KXK', name: 'Komsomolsk-on-Amur Airport', city: 'Komsomolsk-on-Amur' },
  { icao: 'LTAN', iata: 'KYA', name: 'Konya Airport', city: 'Konya' },
  { icao: 'LGKO', iata: 'KGS', name: 'Kos International Airport "Ippokratis"', city: 'Kos Island' },
  { icao: 'UUBA', iata: 'KMW', name: 'Kostroma Sokerkino Airport', city: 'Kostroma' },
  { icao: 'ULKK', iata: 'KSZ', name: 'Kotlas Airport', city: 'Kotlas' },
  { icao: 'LGKZ', iata: 'KZI', name: 'Kozani National Airport Filippos', city: 'Kozani' },
  { icao: 'LZKZ', iata: 'KSC', name: 'Košice International Airport', city: 'Košice' },
  { icao: 'EPKK', iata: 'KRK', name: 'Kraków John Paul II International Airport', city: 'Balice' },
  { icao: 'ESNK', iata: 'KRF', name: 'Kramfors-Sollefteå Höga Kusten Airport', city: 'Nyland' },
  { icao: 'URKK', iata: 'KRR', name: 'Krasnodar Pashkovsky International Airport', city: 'Krasnodar' },
  { icao: 'UNKM', iata: 'KCY', name: 'Krasnoyarsk Cheremshanka Airport', city: 'Krasnoyarsk' },
  { icao: 'UNKL', iata: 'KJA', name: 'Krasnoyarsk International Airport', city: 'Krasnoyarsk' },
  { icao: 'ENCN', iata: 'KRS', name: 'Kristiansand Airport', city: 'Kristiansand(Kjevik)' },
  { icao: 'ENKB', iata: 'KSU', name: 'Kristiansund Airport, Kvernberget', city: 'Kvernberget' },
  { icao: 'UKDR', iata: 'KWG', name: 'Kryvyi Rih International Airport', city: 'Kryvyi Rih' },
  { icao: 'EFKU', iata: 'KUO', name: 'Kuopio Airport', city: 'Kuopio / Siilinjärvi' },
  { icao: 'USCC', iata: 'CEK', name: 'Kurchatov Chelyabinsk International Airport', city: 'Chelyabinsk' },
  { icao: 'EEKE', iata: 'URE', name: 'Kuressaare Airport', city: 'Kuressaare' },
  { icao: 'USUU', iata: 'KRO', name: 'Kurgan Airport', city: 'Kurgan' },
  { icao: 'UUOK', iata: 'URS', name: 'Kursk East Airport', city: 'Kursk' },
  { icao: 'UWWW', iata: 'KUF', name: 'Kurumoch International Airport', city: 'Samara' },
  { icao: 'EFKS', iata: 'KAO', name: 'Kuusamo Airport', city: 'Kuusamo' },
  { icao: 'UNKY', iata: 'KYZ', name: 'Kyzyl Airport', city: 'Kyzyl' },
  { icao: 'EEKA', iata: 'KDL', name: 'Kärdla Airport', city: 'Kärdla' },
  { icao: 'GCLA', iata: 'SPC', name: 'La Palma Airport', city: 'Sta Cruz de la Palma, La Palma Island' },
  { icao: 'LFBH', iata: 'LRH', name: 'La Rochelle Île de Ré Airport', city: 'La Rochelle' },
  { icao: 'LPLA', iata: 'TER', name: 'Lajes Airport', city: 'Praia da Vitória' },
  { icao: 'ENNA', iata: 'LKL', name: 'Lakselv Airport, Banak', city: 'Lakselv' },
  { icao: 'LICA', iata: 'SUF', name: 'Lamezia Terme Sant\'Eufemia International Airport', city: 'Lamezia Terme (CZ)' },
  { icao: 'LICD', iata: 'LMP', name: 'Lampedusa Airport', city: 'Lampedusa' },
  { icao: 'EFLP', iata: 'LPP', name: 'Lappeenranta Airport', city: 'Lappeenranta' },
  { icao: 'LCLK', iata: 'LCA', name: 'Larnaca International Airport', city: 'Larnaca' },
  { icao: 'LFRM', iata: 'LME', name: 'Le Mans-Arnage Airport', city: 'Le Mans, Sarthe' },
  { icao: 'EGNM', iata: 'LBA', name: 'Leeds Bradford Airport', city: 'Leeds, West Yorkshire' },
  { icao: 'LCGK', iata: 'GEC', name: 'Lefkoniko Airport / Geçitkale Air Base', city: 'Lefkoniko (Geçitkale)' },
  { icao: 'EDDP', iata: 'LEJ', name: 'Leipzig/Halle Airport', city: 'Schkeuditz' },
  { icao: 'ENLK', iata: 'LKN', name: 'Leknes Airport', city: 'Leknes' },
  { icao: 'EETN', iata: 'TLL', name: 'Lennart Meri Tallinn Airport', city: 'Tallinn' },
  { icao: 'UERL', iata: 'ULK', name: 'Lensk Airport', city: 'Lensk' },
  { icao: 'LKMT', iata: 'OSR', name: 'Leoš Janáček Airport Ostrava', city: 'Mošnov' },
  { icao: 'LELN', iata: 'LEN', name: 'León Airport', city: 'La Virgen del Camino' },
  { icao: 'EVLA', iata: 'LPX', name: 'Liepāja International Airport', city: 'Liepāja' },
  { icao: 'LFQQ', iata: 'LIL', name: 'Lille Airport', city: 'Lesquin' },
  { icao: 'LFBL', iata: 'LIG', name: 'Limoges Airport', city: 'Limoges/Bellegarde' },
  { icao: 'ESSL', iata: 'LPI', name: 'Linköping City Airport', city: 'Linköping' },
  { icao: 'LOWL', iata: 'LNZ', name: 'Linz-Hörsching Airport', city: 'Linz' },
  { icao: 'UUOL', iata: 'LPK', name: 'Lipetsk Airport', city: 'Lipetsk' },
  { icao: 'LPPT', iata: 'LIS', name: 'Lisbon Humberto Delgado Airport', city: 'Lisbon' },
  { icao: 'EGGP', iata: 'LPL', name: 'Liverpool John Lennon Airport', city: 'Liverpool' },
  { icao: 'EBLG', iata: 'LGG', name: 'Liège Airport', city: 'Grâce-Hollogne' },
  { icao: 'LJLJ', iata: 'LJU', name: 'Ljubljana Jože Pučnik Airport', city: 'Zgornji Brnik' },
  { icao: 'LEDA', iata: 'ILD', name: 'Lleida-Alguaire Airport', city: 'Lleida' },
  { icao: 'EGLC', iata: 'LCY', name: 'London City Airport', city: 'London' },
  { icao: 'EGKK', iata: 'LGW', name: 'London Gatwick Airport', city: 'London' },
  { icao: 'EGLL', iata: 'LHR', name: 'London Heathrow Airport', city: 'London' },
  { icao: 'EGGW', iata: 'LTN', name: 'London Luton Airport', city: 'Luton, Luton' },
  { icao: 'EGMC', iata: 'SEN', name: 'London Southend Airport', city: 'Southend-on-Sea, Essex' },
  { icao: 'EGSS', iata: 'STN', name: 'London Stansted Airport', city: 'London, Essex' },
  { icao: 'LFRH', iata: 'LRT', name: 'Lorient South Brittany (Bretagne Sud) Airport', city: 'Lorient/Lann/Bihoué' },
  { icao: 'EPLB', iata: 'LUZ', name: 'Lublin Airport', city: 'Lublin' },
  { icao: 'LSZA', iata: 'LUG', name: 'Lugano Airport', city: 'Agno' },
  { icao: 'ESPA', iata: 'LLA', name: 'Luleå Airport', city: 'Luleå' },
  { icao: 'ELLX', iata: 'LUX', name: 'Luxembourg-Findel International Airport', city: 'Luxembourg' },
  { icao: 'UKLL', iata: 'LWO', name: 'Lviv International Airport', city: 'Lviv' },
  { icao: 'ESNL', iata: 'LYC', name: 'Lycksele Airport', city: 'Lycksele' },
  { icao: 'LFLL', iata: 'LYS', name: 'Lyon Saint-Exupéry Airport', city: 'Colombier-Saugnieu, Rhône' },
  { icao: 'EDHL', iata: 'LBC', name: 'Lübeck Blankensee Airport', city: 'Lübeck' },
  { icao: 'LZIB', iata: 'BTS', name: 'M. R. Štefánik Airport', city: 'Bratislava' },
  { icao: 'EHBK', iata: 'MST', name: 'Maastricht Aachen Airport', city: 'Maastricht' },
  { icao: 'URMS', iata: 'IGT', name: 'Magas Airport', city: 'Sunzha' },
  { icao: 'USCM', iata: 'MQF', name: 'Magnitogorsk International Airport', city: 'Magnitogorsk' },
  { icao: 'URML', iata: 'MCX', name: 'Makhachkala Uytash International Airport', city: 'Makhachkala' },
  { icao: 'LTAT', iata: 'MLX', name: 'Malatya Erhaç Airport', city: 'Malatya' },
  { icao: 'ESMS', iata: 'MMX', name: 'Malmö Sturup Airport', city: 'Malmö' },
  { icao: 'LMML', iata: 'MLA', name: 'Malta International Airport', city: 'Valletta' },
  { icao: 'EGCC', iata: 'MAN', name: 'Manchester Airport', city: 'Manchester, Greater Manchester' },
  { icao: 'EDFM', iata: 'MHG', name: 'Mannheim-City Airport', city: 'Mannheim' },
  { icao: 'LRBM', iata: 'BAY', name: 'Maramureș International Airport', city: 'Tăuții-Măgherăuș' },
  { icao: 'LIPY', iata: 'AOI', name: 'Marche Airport', city: 'Falconara Marittima (AN)' },
  { icao: 'LTCR', iata: 'MQM', name: 'Mardin Airport', city: 'Mardin' },
  { icao: 'LJMB', iata: 'MBX', name: 'Maribor Edvard Rusjan Airport', city: 'Maribor' },
  { icao: 'EFMA', iata: 'MHQ', name: 'Mariehamn Airport', city: 'Mariehamn' },
  { icao: 'LIRJ', iata: 'EBA', name: 'Marina di Campo Airport', city: 'Campo nell\'Elba (LI)' },
  { icao: 'UKCM', iata: 'MPW', name: 'Mariupol International Airport', city: 'Mariupol' },
  { icao: 'LFML', iata: 'MRS', name: 'Marseille Provence Airport', city: 'Marignane, Bouches-du-Rhône' },
  { icao: 'ENMH', iata: 'MEH', name: 'Mehamn Airport', city: 'Mehamn' },
  { icao: 'GEML', iata: 'MLN', name: 'Melilla Airport', city: 'Melilla' },
  { icao: 'EDJA', iata: 'FMM', name: 'Memmingen Allgau Airport', city: 'Memmingen' },
  { icao: 'LEMH', iata: 'MAH', name: 'Menorca Airport', city: 'Mahón (Maó)' },
  { icao: 'LFJL', iata: 'ETZ', name: 'Metz-Nancy-Lorraine Airport', city: 'Goin' },
  { icao: 'EKKA', iata: 'KRP', name: 'Midtjyllands Airport / Air Base Karup', city: 'Karup' },
  { icao: 'LRCK', iata: 'CND', name: 'Mihail Kogălniceanu International Airport', city: 'Constanța' },
  { icao: 'LIMC', iata: 'MXP', name: 'Milan Malpensa International Airport', city: 'Ferno (VA)' },
  { icao: 'LIML', iata: 'LIN', name: 'Milano Linate Airport', city: 'Segrate (MI)' },
  { icao: 'LTFE', iata: 'BJV', name: 'Milas Bodrum International Airport', city: 'Bodrum' },
  { icao: 'URMM', iata: 'MRV', name: 'Mineralnye Vody Airport', city: 'Mineralnyye Vody' },
  { icao: 'UMMS', iata: 'MSQ', name: 'Minsk National Airport', city: 'Minsk' },
  { icao: 'UERR', iata: 'MJZ', name: 'Mirny Airport', city: 'Mirny' },
  { icao: 'ENRA', iata: 'MQN', name: 'Mo i Rana Airport, Røssvoll', city: 'Mo i Rana' },
  { icao: 'UMOO', iata: 'MVQ', name: 'Mogilev Airport', city: 'Mogilev' },
  { icao: 'ENML', iata: 'MOL', name: 'Molde Airport, Årø', city: 'Årø' },
  { icao: 'UEMA', iata: 'MQJ', name: 'Moma Airport', city: 'Khonuu' },
  { icao: 'LFMT', iata: 'MPL', name: 'Montpellier-Méditerranée Airport', city: 'Montpellier/Méditerranée' },
  { icao: 'ESKM', iata: 'MXX', name: 'Mora Airport', city: 'Mora' },
  { icao: 'LYKV', iata: 'KVO', name: 'Morava Airport', city: 'Kraljevo' },
  { icao: 'ENMS', iata: 'MJF', name: 'Mosjøen Airport, Kjærstad', city: 'Mosjøen' },
  { icao: 'LQMO', iata: 'OMO', name: 'Mostar International Airport', city: 'Mostar' },
  { icao: 'EDDM', iata: 'MUC', name: 'Munich Airport', city: 'Munich' },
  { icao: 'LTCK', iata: 'MSR', name: 'Muş Airport', city: 'Muş' },
  { icao: 'LGMK', iata: 'JMK', name: 'Mykonos Island National Airport', city: 'Mykonos' },
  { icao: 'LGMT', iata: 'MJT', name: 'Mytilene International Airport', city: 'Mytilene' },
  { icao: 'LEMG', iata: 'AGP', name: 'Málaga-Costa del Sol Airport', city: 'Málaga' },
  { icao: 'EDDG', iata: 'FMO', name: 'Münster Osnabrück Airport', city: 'Greven' },
  { icao: 'USMM', iata: 'NYM', name: 'Nadym Airport', city: 'Nadym' },
  { icao: 'URMN', iata: 'NAL', name: 'Nalchik Airport', city: 'Nalchik' },
  { icao: 'LFRS', iata: 'NTE', name: 'Nantes Atlantique Airport', city: 'Nantes' },
  { icao: 'LIRN', iata: 'NAP', name: 'Naples International Airport', city: 'Napoli' },
  { icao: 'ULAM', iata: 'NNM', name: 'Naryan Mar Airport', city: 'Naryan Mar' },
  { icao: 'LGBL', iata: 'VOL', name: 'Nea Anchialos National Airport', city: 'Nea Anchialos' },
  { icao: 'USRN', iata: 'NFG', name: 'Nefteyugansk Airport', city: 'Nefteyugansk' },
  { icao: 'LTAZ', iata: 'NAV', name: 'Nevşehir Kapadokya Airport', city: 'Nevşehir' },
  { icao: 'EGNT', iata: 'NCL', name: 'Newcastle International Airport', city: 'Newcastle upon Tyne, Tyne and Wear' },
  { icao: 'LFMN', iata: 'NCE', name: 'Nice-Côte d\'Azur Airport', city: 'Nice, Alpes-Maritimes' },
  { icao: 'UHNN', iata: 'NLI', name: 'Nikolayevsk-na-Amure Airport', city: 'Nikolayevsk-na-Amure Airport' },
  { icao: 'USNN', iata: 'NJC', name: 'Nizhnevartovsk Airport', city: 'Nizhnevartovsk' },
  { icao: 'UWGG', iata: 'GOJ', name: 'Nizhny Novgorod / Strigino International Airport', city: 'Nizhny Novgorod' },
  { icao: 'LYNI', iata: 'INI', name: 'Niš Constantine the Great Airport', city: 'Niš' },
  { icao: 'ESSP', iata: 'NRK', name: 'Norrköping Airport', city: 'Norrköping' },
  { icao: 'EGSH', iata: 'NWI', name: 'Norwich Airport', city: 'Norwich, Norfolk' },
  { icao: 'UNNT', iata: 'OVB', name: 'Novosibirsk Tolmachevo Airport', city: 'Novosibirsk' },
  { icao: 'USMU', iata: 'NUX', name: 'Novy Urengoy Airport', city: 'Novy Urengoy' },
  { icao: 'USRO', iata: 'NOJ', name: 'Noyabrsk Airport', city: 'Noyabrsk' },
  { icao: 'EDDN', iata: 'NUE', name: 'Nuremberg Airport', city: 'Nuremberg' },
  { icao: 'USHN', iata: 'NYA', name: 'Nyagan Airport', city: 'Nyagan' },
  { icao: 'LFTW', iata: 'FNI', name: 'Nîmes-Arles-Camargue Airport', city: 'Nîmes/Garons' },
  { icao: 'EKOD', iata: 'ODE', name: 'Odense Hans Christian Andersen Airport', city: 'Odense' },
  { icao: 'UKOO', iata: 'ODS', name: 'Odesa International Airport', city: 'Odesa' },
  { icao: 'LWOH', iata: 'OHD', name: 'Ohrid St. Paul the Apostle Airport', city: 'Ohrid' },
  { icao: 'UHOO', iata: 'OHO', name: 'Okhotsk Airport', city: 'Okhotsk' },
  { icao: 'LIEO', iata: 'OLB', name: 'Olbia Costa Smeralda Airport', city: 'Olbia (SS)' },
  { icao: 'EPSY', iata: 'SZY', name: 'Olsztyn-Mazury Airport', city: 'Szymany' },
  { icao: 'UEMO', iata: 'OLZ', name: 'Olyokminsk Airport', city: 'Olyokminsk' },
  { icao: 'UNOO', iata: 'OMS', name: 'Omsk Central Airport', city: 'Omsk' },
  { icao: 'LROD', iata: 'OMR', name: 'Oradea International Airport', city: 'Oradea' },
  { icao: 'LTCB', iata: 'OGU', name: 'Ordu–Giresun Airport', city: 'Ordu' },
  { icao: 'UWOO', iata: 'REN', name: 'Orenburg Central Airport', city: 'Orenburg' },
  { icao: 'UWOR', iata: 'OSW', name: 'Orsk Airport', city: 'Orsk' },
  { icao: 'LDOS', iata: 'OSI', name: 'Osijek Airport', city: 'Osijek(Klisa)' },
  { icao: 'ENGM', iata: 'OSL', name: 'Oslo-Gardermoen International Airport', city: 'Oslo (Gardermoen)' },
  { icao: 'EBOS', iata: 'OST', name: 'Ostend-Bruges International Airport', city: 'Oostende' },
  { icao: 'EFOU', iata: 'OUL', name: 'Oulu Airport', city: 'Oulu / Oulunsalo' },
  { icao: 'EDLP', iata: 'PAD', name: 'Paderborn Lippstadt Airport', city: 'Büren' },
  { icao: 'EYPA', iata: 'PLQ', name: 'Palanga International Airport', city: 'Palanga' },
  { icao: 'LEPA', iata: 'PMI', name: 'Palma de Mallorca Airport', city: 'Palma de Mallorca' },
  { icao: 'LEPP', iata: 'PNA', name: 'Pamplona Airport', city: 'Pamplona' },
  { icao: 'LICG', iata: 'PNL', name: 'Pantelleria Airport', city: 'Pantelleria (TP)' },
  { icao: 'LCPH', iata: 'PFO', name: 'Paphos International Airport', city: 'Paphos' },
  { icao: 'LKPD', iata: 'PED', name: 'Pardubice Airport', city: 'Pardubice' },
  { icao: 'LFPB', iata: 'LBG', name: 'Paris-Le Bourget International Airport', city: 'Paris' },
  { icao: 'LFPO', iata: 'ORY', name: 'Paris-Orly Airport', city: 'Paris (Orly, Val-de-Marne)' },
  { icao: 'LIMP', iata: 'PMF', name: 'Parma Airport', city: 'Parma (PR)' },
  { icao: 'LGRX', iata: 'GPA', name: 'Patras Araxos Agamemnon Airport', city: 'Patras' },
  { icao: 'LFBP', iata: 'PUF', name: 'Pau Pyrénées Airport', city: 'Pau/Pyrénées (Uzein)' },
  { icao: 'UUYP', iata: 'PEX', name: 'Pechora Airport', city: 'Pechora' },
  { icao: 'UWPP', iata: 'PEZ', name: 'Penza Airport', city: 'Penza' },
  { icao: 'USPP', iata: 'PEE', name: 'Perm International Airport', city: 'Perm' },
  { icao: 'LFMP', iata: 'PGF', name: 'Perpignan-Rivesaltes (Llabanère) Airport', city: 'Perpignan/Rivesaltes' },
  { icao: 'LIRZ', iata: 'PEG', name: 'Perugia San Francesco d\'Assisi – Umbria International Airport', city: 'Perugia (PG)' },
  { icao: 'ULPB', iata: 'PES', name: 'Petrozavodsk Airport', city: 'Petrozavodsk' },
  { icao: 'UHMP', iata: 'PWE', name: 'Pevek Airport', city: 'Apapelgino' },
  { icao: 'LPPI', iata: 'PIX', name: 'Pico Airport', city: 'Pico Island' },
  { icao: 'LESU', iata: 'LEU', name: 'Pirineus - la Seu d\'Urgel Airport', city: 'La Seu d\'Urgell Pyrenees and Andorra' },
  { icao: 'LIRP', iata: 'PSA', name: 'Pisa International Airport', city: 'Pisa (PI)' },
  { icao: 'UEEE', iata: 'YKS', name: 'Platon Oyunsky Yakutsk International Airport', city: 'Yakutsk' },
  { icao: 'URRP', iata: 'ROV', name: 'Platov International Airport', city: 'Rostov-on-Don' },
  { icao: 'LBPD', iata: 'PDV', name: 'Plovdiv International Airport', city: 'Plovdiv' },
  { icao: 'USKK', iata: 'KVX', name: 'Pobedilovo Airport', city: 'Kirov' },
  { icao: 'LYPG', iata: 'TGD', name: 'Podgorica Airport / Podgorica Golubovci Airbase', city: 'Podgorica' },
  { icao: 'LFBI', iata: 'PIS', name: 'Poitiers-Biard Airport', city: 'Poitiers/Biard' },
  { icao: 'UERP', iata: 'PYJ', name: 'Polyarny Airport', city: 'Yakutia' },
  { icao: 'LZTT', iata: 'TAT', name: 'Poprad-Tatry Airport', city: 'Poprad' },
  { icao: 'EFPO', iata: 'POR', name: 'Pori Airport', city: 'Pori' },
  { icao: 'LPPM', iata: 'PRM', name: 'Portimão Airport', city: 'Portimão' },
  { icao: 'LPPS', iata: 'PXO', name: 'Porto Santo Airport', city: 'Vila Baleira' },
  { icao: 'EPPO', iata: 'POZ', name: 'Poznań-Ławica Airport', city: 'Poznań' },
  { icao: 'ULOO', iata: 'PKV', name: 'Princess Olga Pskov International Airport', city: 'Pskov' },
  { icao: 'BKPR', iata: 'PRN', name: 'Priština Adem Jashari International Airport', city: 'Prishtina' },
  { icao: 'LDPL', iata: 'PUY', name: 'Pula Airport', city: 'Pula' },
  { icao: 'ULLI', iata: 'LED', name: 'Pulkovo Airport', city: 'St. Petersburg' },
  { icao: 'EEPU', iata: 'EPU', name: 'Pärnu Airport', city: 'Pärnu' },
  { icao: 'LHPP', iata: 'PEV', name: 'Pécs-Pogány International Airport', city: 'Pécs' },
  { icao: 'LICR', iata: 'REG', name: 'Reggio Calabria Airport', city: 'Reggio Calabria' },
  { icao: 'LEMI', iata: 'RMU', name: 'Region of Murcia International Airport', city: 'Corvera' },
  { icao: 'LFRN', iata: 'RNS', name: 'Rennes-Saint-Jacques Airport', city: 'Saint-Jacques-de-la-Lande, Ille-et-Vilaine' },
  { icao: 'LERS', iata: 'REU', name: 'Reus Airport', city: 'Reus' },
  { icao: 'BIRK', iata: 'RKV', name: 'Reykjavík Domestic Airport', city: 'Reykjavík' },
  { icao: 'LGRP', iata: 'RHO', name: 'Rhodes International Airport "Diagoras"', city: 'Rhodes' },
  { icao: 'EVRA', iata: 'RIX', name: 'Riga International Airport', city: 'Riga' },
  { icao: 'LDRI', iata: 'RJK', name: 'Rijeka Airport', city: 'Rijeka(Omišalj)' },
  { icao: 'UKLR', iata: 'RWN', name: 'Rivne International Airport', city: 'Rivne' },
  { icao: 'LTFO', iata: 'RZV', name: 'Rize–Artvin Airport', city: 'Rize' },
  { icao: 'LFCR', iata: 'RDZ', name: 'Rodez–Aveyron Airport', city: 'Rodez/Marcillac' },
  { icao: 'LIRF', iata: 'FCO', name: 'Rome–Fiumicino Leonardo da Vinci International Airport', city: 'Rome' },
  { icao: 'ESDF', iata: 'RNB', name: 'Ronneby Airport', city: 'Ronneby' },
  { icao: 'USTR', iata: 'TJM', name: 'Roshchino International Airport', city: 'Tyumen' },
  { icao: 'ETNL', iata: 'RLG', name: 'Rostock-Laage Airport', city: 'Laage' },
  { icao: 'EHRD', iata: 'RTM', name: 'Rotterdam The Hague Airport', city: 'Rotterdam' },
  { icao: 'EFRO', iata: 'RVN', name: 'Rovaniemi Airport', city: 'Rovaniemi' },
  { icao: 'EPRZ', iata: 'RZE', name: 'Rzeszów-Jasionka Airport', city: 'Jasionka' },
  { icao: 'ENRO', iata: 'RRS', name: 'Røros Airport', city: 'Røros' },
  { icao: 'ENRM', iata: 'RVK', name: 'Rørvik Airport, Ryum', city: 'Rørvik' },
  { icao: 'EDDR', iata: 'SCN', name: 'Saarbrücken Airport', city: 'Saarbrücken' },
  { icao: 'USDA', iata: 'SBT', name: 'Sabetta International Airport', city: 'Sabetta' },
  { icao: 'LFRZ', iata: 'SNR', name: 'Saint-Nazaire-Montoir Airport', city: 'Saint-Nazaire/Montoir' },
  { icao: 'LESA', iata: 'SLM', name: 'Salamanca Airport', city: 'Salamanca' },
  { icao: 'USDD', iata: 'SLY', name: 'Salekhard Airport', city: 'Salekhard' },
  { icao: 'LIRI', iata: 'QSR', name: 'Salerno Costa d\'Amalfi Airport', city: 'Salerno' },
  { icao: 'LOWS', iata: 'SZG', name: 'Salzburg Airport', city: 'Salzburg' },
  { icao: 'LGSM', iata: 'SMI', name: 'Samos Airport', city: 'Samos Island' },
  { icao: 'LTFH', iata: 'SZF', name: 'Samsun-Çarşamba Airport', city: 'Samsun' },
  { icao: 'LESO', iata: 'EAS', name: 'San Sebastián Airport', city: 'Hondarribia' },
  { icao: 'ENTO', iata: 'TRF', name: 'Sandefjord Airport, Torp', city: 'Sandefjord(Torp)' },
  { icao: 'ENST', iata: 'SSJ', name: 'Sandnessjøen Airport, Stokka', city: 'Alstahaug' },
  { icao: 'LSZR', iata: 'ACH', name: 'Sankt Gallen Altenrhein Airport', city: 'St. Gallen' },
  { icao: 'LPAZ', iata: 'SMA', name: 'Santa Maria Airport', city: 'Vila do Porto' },
  { icao: 'LEST', iata: 'SCQ', name: 'Santiago-Rosalía de Castro Airport', city: 'Santiago de Compostela' },
  { icao: 'LGSR', iata: 'JTR', name: 'Santorini International Airport', city: 'Santorini Island' },
  { icao: 'LQSA', iata: 'SJJ', name: 'Sarajevo International Airport', city: 'Sarajevo' },
  { icao: 'UWPS', iata: 'SKX', name: 'Saransk International Airport', city: 'Saransk' },
  { icao: 'UERS', iata: 'SYS', name: 'Saskylakh Airport', city: 'Saskylakh' },
  { icao: 'LRSM', iata: 'SUJ', name: 'Satu Mare International Airport', city: 'Satu Mare' },
  { icao: 'EFSA', iata: 'SVL', name: 'Savonlinna Airport', city: 'Savonlinna' },
  { icao: 'ESKS', iata: 'SCR', name: 'Scandinavian Mountains Airport', city: 'Malung-Sälen' },
  { icao: 'ETMN', iata: 'FCN', name: 'Sea-Airport Cuxhaven/Nordholz / Nordholz Naval Airbase', city: 'Wurster Nordseeküste' },
  { icao: 'LEXJ', iata: 'SDR', name: 'Seve Ballesteros-Santander Airport', city: 'Santander' },
  { icao: 'UNIS', iata: 'VEO', name: 'Severo-Yeniseysk Airport', city: 'Severo-Yeniseysk' },
  { icao: 'LEZL', iata: 'SVQ', name: 'Seville Airport', city: 'Seville' },
  { icao: 'EINN', iata: 'SNN', name: 'Shannon Airport', city: 'Shannon' },
  { icao: 'UUEE', iata: 'SVO', name: 'Sheremetyevo International Airport', city: 'Moscow' },
  { icao: 'LRSB', iata: 'SBZ', name: 'Sibiu International Airport', city: 'Sibiu' },
  { icao: 'UKFF', iata: 'SIP', name: 'Simferopol International Airport', city: 'Simferopol' },
  { icao: 'LTCM', iata: 'NOP', name: 'Sinop Airport', city: 'Sinop' },
  { icao: 'LGST', iata: 'JSH', name: 'Sitia Airport', city: 'Crete Island' },
  { icao: 'ESNS', iata: 'SFT', name: 'Skellefteå Airport', city: 'Skellefteå' },
  { icao: 'LGSK', iata: 'JSI', name: 'Skiathos Island National Airport', city: 'Skiathos' },
  { icao: 'LWSK', iata: 'SKP', name: 'Skopje International Airport', city: 'Ilinden' },
  { icao: 'LZSL', iata: 'SLD', name: 'Sliač Airport', city: 'Sliač' },
  { icao: 'URSS', iata: 'AER', name: 'Sochi International Airport', city: 'Sochi' },
  { icao: 'LBSF', iata: 'SOF', name: 'Sofia Airport', city: 'Sofia' },
  { icao: 'UHMM', iata: 'GDX', name: 'Sokol Airport', city: 'Magadan' },
  { icao: 'EPSC', iata: 'SZZ', name: 'Solidarity Szczecin–Goleniów Airport', city: 'Szczecin(Glewice)' },
  { icao: 'EGHI', iata: 'SOU', name: 'Southampton Airport', city: 'Southampton' },
  { icao: 'USHS', iata: 'OVS', name: 'Sovetskiy Airport', city: 'Sovetskiy' },
  { icao: 'UNWW', iata: 'NOZ', name: 'Spichenkovo Airport', city: 'Novokuznetsk' },
  { icao: 'LDSP', iata: 'SPU', name: 'Split Saint Jerome Airport', city: 'Split' },
  { icao: 'UESK', iata: 'SEK', name: 'Srednekolymsk Airport', city: 'Srednekolymsk' },
  { icao: 'UUBK', iata: 'RYB', name: 'Staroselye Airport', city: 'Rybinsk' },
  { icao: 'ENZV', iata: 'SVG', name: 'Stavanger Airport, Sola', city: 'Stavanger' },
  { icao: 'URMT', iata: 'STW', name: 'Stavropol Shpakovskoye Airport', city: 'Stavropol' },
  { icao: 'ESKN', iata: 'NYO', name: 'Stockholm Skavsta Airport', city: 'Nyköping' },
  { icao: 'ESOW', iata: 'VST', name: 'Stockholm Västerås Airport', city: 'Stockholm / Västerås' },
  { icao: 'ESSA', iata: 'ARN', name: 'Stockholm-Arlanda Airport', city: 'Stockholm' },
  { icao: 'ESSB', iata: 'BMA', name: 'Stockholm-Bromma Airport', city: 'Stockholm' },
  { icao: 'ENSK', iata: 'SKN', name: 'Stokmarknes Airport, Skagen', city: 'Hadsel' },
  { icao: 'ENSO', iata: 'SRP', name: 'Stord Airport, Sørstokken', city: 'Leirvik' },
  { icao: 'EGPO', iata: 'SYY', name: 'Stornoway Airport', city: 'Stornoway, Western Isles' },
  { icao: 'LFST', iata: 'SXB', name: 'Strasbourg Airport', city: 'Strasbourg' },
  { icao: 'EDDS', iata: 'STR', name: 'Stuttgart Airport', city: 'Stuttgart' },
  { icao: 'LRSV', iata: 'SCV', name: 'Suceava Ștefan cel Mare International Airport', city: 'Suceava' },
  { icao: 'EGPB', iata: 'LSI', name: 'Sumburgh Airport', city: 'Lerwick, Shetland' },
  { icao: 'ESNN', iata: 'SDL', name: 'Sundsvall-Härnösand Airport', city: 'Sundsvall/ Härnösand' },
  { icao: 'USRR', iata: 'SGC', name: 'Surgut International Airport', city: 'Surgut' },
  { icao: 'ENSB', iata: 'LYR', name: 'Svalbard Airport, Longyear', city: 'Longyearbyen' },
  { icao: 'ENSH', iata: 'SVJ', name: 'Svolvær Airport, Helle', city: 'Svolvær' },
  { icao: 'UUYY', iata: 'SCW', name: 'Syktyvkar Airport', city: 'Syktyvkar' },
  { icao: 'LPSJ', iata: 'SJZ', name: 'São Jorge Airport', city: 'Velas' },
  { icao: 'EKSB', iata: 'SGD', name: 'Sønderborg Airport', city: 'Sønderborg' },
  { icao: 'ENSR', iata: 'SOJ', name: 'Sørkjosen Airport', city: 'Sørkjosen' },
  { icao: 'LTFC', iata: 'ISE', name: 'Süleyman Demirel International Airport', city: 'Isparta' },
  { icao: 'URRT', iata: 'TGK', name: 'Taganrog Yuzhny Airport', city: 'Taganrog' },
  { icao: 'ULAA', iata: 'ARH', name: 'Talagi Airport', city: 'Archangelsk' },
  { icao: 'EFTP', iata: 'TMP', name: 'Tampere-Pirkkala Airport', city: 'Tampere / Pirkkala' },
  { icao: 'LFBT', iata: 'LDE', name: 'Tarbes-Lourdes-Pyrénées Airport', city: 'Tarbes/Lourdes/Pyrénées' },
  { icao: 'EETU', iata: 'TAY', name: 'Tartu Airport', city: 'Tartu' },
  { icao: 'EGNV', iata: 'MME', name: 'Teesside International Airport', city: 'Darlington, Durham' },
  { icao: 'LTBU', iata: 'TEQ', name: 'Tekirdağ Çorlu Airport', city: 'Çorlu' },
  { icao: 'GCXO', iata: 'TFN', name: 'Tenerife Norte-Ciudad de La Laguna Airport', city: 'Tenerife' },
  { icao: 'GCTS', iata: 'TFS', name: 'Tenerife Sur Airport', city: 'Tenerife' },
  { icao: 'LGTS', iata: 'SKG', name: 'Thessaloniki Macedonia International Airport', city: 'Thessaloniki' },
  { icao: 'UEST', iata: 'IKS', name: 'Tiksi Airport', city: 'Tiksi' },
  { icao: 'LRTR', iata: 'TSR', name: 'Timișoara Traian Vuia International Airport', city: 'Timişoara' },
  { icao: 'LATI', iata: 'TIA', name: 'Tirana International Airport Mother Teresa', city: 'Rinas' },
  { icao: 'EGPU', iata: 'TRE', name: 'Tiree Airport', city: 'Balemartine, Argyll and Bute' },
  { icao: 'LYTV', iata: 'TIV', name: 'Tivat Airport', city: 'Tivat' },
  { icao: 'USTJ', iata: 'RMZ', name: 'Tobolsk Remezov Airport', city: 'Tobolsk' },
  { icao: 'LTAW', iata: 'TJK', name: 'Tokat Airport', city: 'Tokat' },
  { icao: 'UNTT', iata: 'TOF', name: 'Tomsk Kamov Airport', city: 'Tomsk' },
  { icao: 'ESST', iata: 'TYF', name: 'Torsby Airport', city: 'Torsby' },
  { icao: 'LFTH', iata: 'TLN', name: 'Toulon-Hyères Airport', city: 'Hyères, Var' },
  { icao: 'LFBO', iata: 'TLS', name: 'Toulouse-Blagnac Airport', city: 'Toulouse/Blagnac' },
  { icao: 'LFOT', iata: 'TUF', name: 'Tours Val de Loire Airport', city: 'Tours, Indre-et-Loire' },
  { icao: 'LTCG', iata: 'TZX', name: 'Trabzon International Airport', city: 'Trabzon' },
  { icao: 'LIPH', iata: 'TSF', name: 'Treviso Airport', city: 'Treviso (TV)' },
  { icao: 'LIPQ', iata: 'TRS', name: 'Trieste Airport', city: 'Ronchi dei Legionari/Trieste' },
  { icao: 'ESGT', iata: 'THN', name: 'Trollhättan-Vänersborg Airport', city: 'Trollhättan' },
  { icao: 'ENTC', iata: 'TOS', name: 'Tromsø Airport', city: 'Tromsø' },
  { icao: 'ENVA', iata: 'TRD', name: 'Trondheim Airport, Værnes', city: 'Trondheim' },
  { icao: 'LIMF', iata: 'TRN', name: 'Turin Airport', city: 'Caselle Torinese (TO)' },
  { icao: 'EFTU', iata: 'TKU', name: 'Turku Airport', city: 'Turku' },
  { icao: 'LQTZ', iata: 'TZL', name: 'Tuzla International Airport', city: 'Dubrave Gornje' },
  { icao: 'LRTM', iata: 'TGM', name: 'Târgu Mureş Transilvania International Airport', city: 'Recea' },
  { icao: 'UWUU', iata: 'UFA', name: 'Ufa International Airport', city: 'Ufa' },
  { icao: 'UHMA', iata: 'DYR', name: 'Ugolny Yuri Ryktheu Airport', city: 'Anadyr' },
  { icao: 'UUYH', iata: 'UCT', name: 'Ukhta Airport', city: 'Ukhta' },
  { icao: 'UWLL', iata: 'ULV', name: 'Ulyanovsk Baratayevka Airport', city: 'Ulyanovsk' },
  { icao: 'UWLW', iata: 'ULY', name: 'Ulyanovsk Vostochny Airport', city: 'Cherdakly' },
  { icao: 'ESNU', iata: 'UME', name: 'Umeå Airport', city: 'Umeå' },
  { icao: 'USHU', iata: 'URJ', name: 'Uray Airport', city: 'Uray' },
  { icao: 'UUYS', iata: 'USK', name: 'Usinsk Airport', city: 'Usinsk' },
  { icao: 'UITT', iata: 'UKX', name: 'Ust-Kut Airport', city: 'Ust-Kut' },
  { icao: 'UEMT', iata: 'USR', name: 'Ust-Nera Airport', city: 'Ust-Nera' },
  { icao: 'UKLU', iata: 'UDJ', name: 'Uzhhorod International Airport', city: 'Uzhhorod' },
  { icao: 'EFVA', iata: 'VAA', name: 'Vaasa Airport', city: 'Vaasa' },
  { icao: 'ENVD', iata: 'VDS', name: 'Vadsø Airport', city: 'Vadsø' },
  { icao: 'LEVC', iata: 'VLC', name: 'Valencia Airport', city: 'Valencia' },
  { icao: 'LEVD', iata: 'VLL', name: 'Valladolid Airport', city: 'Valladolid' },
  { icao: 'LTCI', iata: 'VAN', name: 'Van Ferit Melen Airport', city: 'Van' },
  { icao: 'UNIW', iata: 'VAQ', name: 'Vanavara Airport', city: 'Vanavara' },
  { icao: 'ENSS', iata: 'VAW', name: 'Vardø Airport, Svartnes', city: 'Vardø' },
  { icao: 'LBWN', iata: 'VAR', name: 'Varna Airport', city: 'Varna' },
  { icao: 'ULWU', iata: 'VUS', name: 'Velikiy Ustyug Airport', city: 'Velikiy Ustyug' },
  { icao: 'LIPZ', iata: 'VCE', name: 'Venice Marco Polo Airport', city: 'Venezia (VE)' },
  { icao: 'LIPX', iata: 'VRN', name: 'Verona Villafranca Valerio Catullo Airport', city: 'Caselle (VR)' },
  { icao: 'LOWW', iata: 'VIE', name: 'Vienna International Airport', city: 'Vienna' },
  { icao: 'LEVX', iata: 'VGO', name: 'Vigo Airport', city: 'Vigo' },
  { icao: 'LPVR', iata: 'VRL', name: 'Vila Real Airport', city: 'Vila Real' },
  { icao: 'ESNV', iata: 'VHM', name: 'Vilhelmina South Lapland Airport', city: 'Vilhelmina' },
  { icao: 'EYVI', iata: 'VNO', name: 'Vilnius International Airport', city: 'Vilnius' },
  { icao: 'UENW', iata: 'VYI', name: 'Vilyuisk Airport', city: 'Vilyuisk' },
  { icao: 'LICT', iata: 'TPS', name: 'Vincenzo Florio Airport Trapani-Birgi', city: 'Trapani (TP)' },
  { icao: 'ESSV', iata: 'VBY', name: 'Visby Airport', city: 'Visby' },
  { icao: 'LEVT', iata: 'VIT', name: 'Vitoria Airport', city: 'Alava' },
  { icao: 'URMO', iata: 'OGZ', name: 'Vladikavkaz Beslan International Airport', city: 'Beslan' },
  { icao: 'UHWW', iata: 'VVO', name: 'Vladivostok International Airport', city: 'Artyom' },
  { icao: 'UUWW', iata: 'VKO', name: 'Vnukovo International Airport', city: 'Moscow' },
  { icao: 'URWW', iata: 'VOG', name: 'Volgograd International Airport', city: 'Volgograd' },
  { icao: 'BIVO', iata: 'VPN', name: 'Vopnafjörður Airport', city: 'Vopnafjörður' },
  { icao: 'UUYW', iata: 'VKT', name: 'Vorkuta Airport', city: 'Vorkuta' },
  { icao: 'UUOO', iata: 'VOZ', name: 'Voronezh International Airport', city: 'Voronezh' },
  { icao: 'LKPR', iata: 'PRG', name: 'Václav Havel Airport Prague', city: 'Prague' },
  { icao: 'EKVG', iata: 'FAE', name: 'Vágar Airport', city: 'Vágar' },
  { icao: 'ESMX', iata: 'VXO', name: 'Växjö Kronoberg Airport', city: 'Växjö' },
  { icao: 'EPWA', iata: 'WAW', name: 'Warsaw Chopin Airport', city: 'Warsaw' },
  { icao: 'EPMO', iata: 'WMI', name: 'Warsaw Modlin Airport', city: 'Nowy Dwór Mazowiecki' },
  { icao: 'EPRA', iata: 'RDO', name: 'Warsaw Radom Airport', city: 'Radom' },
  { icao: 'EDLV', iata: 'NRN', name: 'Weeze (Niederrhein) Airport', city: 'Weeze' },
  { icao: 'EDXW', iata: 'GWT', name: 'Westerland Sylt Airport', city: 'Sylt' },
  { icao: 'EGPC', iata: 'WIC', name: 'Wick John O\'Groats Airport', city: 'Wick' },
  { icao: 'UHPP', iata: 'PKC', name: 'Yelizovo Airport', city: 'Petropavlovsk-Kamchatsky' },
  { icao: 'UNII', iata: 'EIE', name: 'Yeniseysk Airport', city: 'Yeniseysk' },
  { icao: 'UHSS', iata: 'UUS', name: 'Yuzhno-Sakhalinsk International Airport', city: 'Yuzhno-Sakhalinsk' },
  { icao: 'LDZD', iata: 'ZAD', name: 'Zadar Airport', city: 'Zadar' },
  { icao: 'LDZA', iata: 'ZAG', name: 'Zagreb Franjo Tuđman International Airport', city: 'Velika Gorica' },
  { icao: 'LGZA', iata: 'ZTH', name: 'Zakynthos International Airport Dionysios Solomos', city: 'Zakynthos' },
  { icao: 'UKDE', iata: 'OZH', name: 'Zaporizhzhia International Airport', city: 'Zaporizhia' },
  { icao: 'LEZG', iata: 'ZAZ', name: 'Zaragoza Airport', city: 'Zaragoza' },
  { icao: 'UEVV', iata: 'ZIX', name: 'Zhigansk Airport', city: 'Zhigansk' },
  { icao: 'UUBW', iata: 'ZIA', name: 'Zhukovsky International Airport', city: 'Moscow' },
  { icao: 'EPZG', iata: 'IEG', name: 'Zielona Góra-Babimost Airport', city: 'Nowe Kramsko' },
  { icao: 'LTAS', iata: 'ONQ', name: 'Zonguldak Çaycuma Airport', city: 'Zonguldak' },
  { icao: 'UESU', iata: 'ZKP', name: 'Zyryanka Airport', city: 'Zyryanka' },
  { icao: 'LSZH', iata: 'ZRH', name: 'Zürich Airport', city: 'Zurich' },
  { icao: 'ESTA', iata: 'AGH', name: 'Ängelholm-Helsingborg Airport', city: 'Ängelholm' },
  { icao: 'ENAL', iata: 'AES', name: 'Ålesund Airport', city: 'Ålesund' },
  { icao: 'ESNZ', iata: 'OSD', name: 'Åre Östersund Airport', city: 'Östersund' },
  { icao: 'LTBH', iata: 'CKZ', name: 'Çanakkale Airport', city: 'Çanakkale' },
  { icao: 'LTAY', iata: 'DNZ', name: 'Çardak Airport', city: 'Denizli' },
  { icao: 'LTDB', iata: 'COV', name: 'Çukurova International Airport', city: 'Tarsus' },
  { icao: 'BIIS', iata: 'IFJ', name: 'Ísafjörður Airport', city: 'Ísafjörður' },
  { icao: 'ESOE', iata: 'ORB', name: 'Örebro Airport', city: 'Örebro' },
  { icao: 'ESNO', iata: 'OER', name: 'Örnsköldsvik Airport', city: 'Örnsköldsvik' },
  { icao: 'ENOL', iata: 'OLA', name: 'Ørland Airport', city: 'Ørland' },
  { icao: 'ENOV', iata: 'HOV', name: 'Ørsta-Volda Airport, Hovden', city: 'Ørsta' },
  { icao: 'LKCS', iata: 'JCL', name: 'České Budějovice South Bohemian Airport', city: 'České Budějovice' },
  { icao: 'EPLL', iata: 'LCJ', name: 'Łódź Władysław Reymont Airport', city: 'Łódź' },
  { icao: 'LTCS', iata: 'GNY', name: 'Şanlıurfa GAP Airport', city: 'Şanlıurfa' },
  { icao: 'LTCV', iata: 'NKT', name: 'Şırnak Şerafettin Elçi Airport', city: 'Şırnak' },
];
