// All Scottish railway stations (name + CRS code), for the Trains tab picker.
// Source: davwheat/uk-railway-stations (constituentCountry === 'scotland'),
// filtered and sorted by name. CRS codes drive the live Darwin/Huxley lookups.

export const STATIONS = [
  { crs: 'ABD', name: 'Aberdeen' },
  { crs: 'AUR', name: 'Aberdour' },
  { crs: 'AAT', name: 'Achanalt' },
  { crs: 'ACN', name: 'Achnasheen' },
  { crs: 'ACH', name: 'Achnashellach' },
  { crs: 'ADW', name: 'Addiewell' },
  { crs: 'AIR', name: 'Airbles' },
  { crs: 'ADR', name: 'Airdrie' },
  { crs: 'AXP', name: 'Alexandra Parade' },
  { crs: 'ALX', name: 'Alexandria' },
  { crs: 'ALO', name: 'Alloa' },
  { crs: 'ASS', name: 'Alness' },
  { crs: 'ABC', name: 'Altnabreac' },
  { crs: 'AND', name: 'Anderston' },
  { crs: 'ANN', name: 'Annan' },
  { crs: 'ANL', name: 'Anniesland' },
  { crs: 'ARB', name: 'Arbroath' },
  { crs: 'ARD', name: 'Ardgay' },
  { crs: 'AUI', name: 'Ardlui' },
  { crs: 'ADS', name: 'Ardrossan Harbour' },
  { crs: 'ASB', name: 'Ardrossan South Beach' },
  { crs: 'ADN', name: 'Ardrossan Town' },
  { crs: 'AGS', name: 'Argyle Street' },
  { crs: 'ARG', name: 'Arisaig' },
  { crs: 'ARM', name: 'Armadale' },
  { crs: 'ART', name: 'Arrochar & Tarbet' },
  { crs: 'ASF', name: 'Ashfield' },
  { crs: 'ATT', name: 'Attadale' },
  { crs: 'AUK', name: 'Auchinleck' },
  { crs: 'AVM', name: 'Aviemore' },
  { crs: 'AYR', name: 'Ayr' },
  { crs: 'BIO', name: 'Baillieston' },
  { crs: 'BHC', name: 'Balloch Central' },
  { crs: 'BSI', name: 'Balmossie' },
  { crs: 'BNV', name: 'Banavie' },
  { crs: 'BSS', name: 'Barassie' },
  { crs: 'BGI', name: 'Bargeddie' },
  { crs: 'BNL', name: 'Barnhill' },
  { crs: 'BRR', name: 'Barrhead' },
  { crs: 'BRL', name: 'Barrhill' },
  { crs: 'BYL', name: 'Barry Links' },
  { crs: 'BHG', name: 'Bathgate' },
  { crs: 'BRN', name: 'Bearsden' },
  { crs: 'BSL', name: 'Beasdale' },
  { crs: 'BEL', name: 'Beauly' },
  { crs: 'BLG', name: 'Bellgrove' },
  { crs: 'BLH', name: 'Bellshill' },
  { crs: 'BBG', name: 'Bishopbriggs' },
  { crs: 'BPT', name: 'Bishopton' },
  { crs: 'BKR', name: 'Blackridge' },
  { crs: 'BLA', name: 'Blair Atholl' },
  { crs: 'BAI', name: 'Blairhill' },
  { crs: 'BLT', name: 'Blantyre' },
  { crs: 'BGS', name: 'Bogston' },
  { crs: 'BWG', name: 'Bowling' },
  { crs: 'BCN', name: 'Branchton' },
  { crs: 'BRC', name: 'Breich' },
  { crs: 'BEA', name: 'Bridge of Allan' },
  { crs: 'BRO', name: 'Bridge of Orchy' },
  { crs: 'BDG', name: 'Bridgeton' },
  { crs: 'BRA', name: 'Brora' },
  { crs: 'BYF', name: 'Broughty Ferry' },
  { crs: 'BSU', name: 'Brunstane' },
  { crs: 'BUI', name: 'Burnside' },
  { crs: 'BTS', name: 'Burntisland' },
  { crs: 'BUS', name: 'Busby' },
  { crs: 'CAC', name: 'Caldercruix' },
  { crs: 'CBL', name: 'Cambuslang' },
  { crs: 'CMO', name: 'Camelon' },
  { crs: 'CBX', name: 'Cameron Bridge' },
  { crs: 'CDD', name: 'Cardenden' },
  { crs: 'CDO', name: 'Cardonald' },
  { crs: 'CDR', name: 'Cardross' },
  { crs: 'CRF', name: 'Carfin' },
  { crs: 'CLU', name: 'Carluke' },
  { crs: 'CML', name: 'Carmyle' },
  { crs: 'CAN', name: 'Carnoustie' },
  { crs: 'CAY', name: 'Carntyne' },
  { crs: 'CAG', name: 'Carrbridge' },
  { crs: 'CRS', name: 'Carstairs' },
  { crs: 'CDY', name: 'Cartsdyke' },
  { crs: 'CCT', name: 'Cathcart' },
  { crs: 'CHC', name: 'Charing Cross (Glasgow)' },
  { crs: 'CTE', name: 'Chatelherault' },
  { crs: 'CKS', name: 'Clarkston' },
  { crs: 'CEA', name: 'Cleland' },
  { crs: 'CYK', name: 'Clydebank' },
  { crs: 'CBC', name: 'Coatbridge Central' },
  { crs: 'CBS', name: 'Coatbridge Sunnyside' },
  { crs: 'COA', name: 'Coatdyke' },
  { crs: 'CON', name: 'Connel Ferry' },
  { crs: 'CBD', name: 'Conon Bridge' },
  { crs: 'CKH', name: 'Corkerhill' },
  { crs: 'CPA', name: 'Corpach' },
  { crs: 'CRR', name: 'Corrour' },
  { crs: 'COW', name: 'Cowdenbeath' },
  { crs: 'CGD', name: 'Craigendoran' },
  { crs: 'CNR', name: 'Crianlarich' },
  { crs: 'CFF', name: 'Croftfoot' },
  { crs: 'CKT', name: 'Crookston' },
  { crs: 'COI', name: 'Crosshill' },
  { crs: 'CMY', name: 'Crossmyloof' },
  { crs: 'CRO', name: 'Croy' },
  { crs: 'CUA', name: 'Culrain' },
  { crs: 'CUB', name: 'Cumbernauld' },
  { crs: 'CUP', name: 'Cupar' },
  { crs: 'CUH', name: 'Curriehill' },
  { crs: 'DAG', name: 'Dalgety Bay' },
  { crs: 'DAL', name: 'Dalmally' },
  { crs: 'DAK', name: 'Dalmarnock' },
  { crs: 'DAM', name: 'Dalmeny' },
  { crs: 'DMR', name: 'Dalmuir' },
  { crs: 'DLR', name: 'Dalreoch' },
  { crs: 'DLY', name: 'Dalry' },
  { crs: 'DLW', name: 'Dalwhinnie' },
  { crs: 'DIN', name: 'Dingwall' },
  { crs: 'DRM', name: 'Drem' },
  { crs: 'DMC', name: 'Drumchapel' },
  { crs: 'DFR', name: 'Drumfrochar' },
  { crs: 'DRU', name: 'Drumgelloch' },
  { crs: 'DMY', name: 'Drumry' },
  { crs: 'DRN', name: 'Duirinish' },
  { crs: 'DST', name: 'Duke Street' },
  { crs: 'DBC', name: 'Dumbarton Central' },
  { crs: 'DBE', name: 'Dumbarton East' },
  { crs: 'DUM', name: 'Dumbreck' },
  { crs: 'DMF', name: 'Dumfries' },
  { crs: 'DUN', name: 'Dunbar' },
  { crs: 'DBL', name: 'Dunblane' },
  { crs: 'DCG', name: 'Duncraig' },
  { crs: 'DEE', name: 'Dundee' },
  { crs: 'DFE', name: 'Dunfermline City' },
  { crs: 'DFL', name: 'Dunfermline Queen Margaret' },
  { crs: 'DKD', name: 'Dunkeld & Birnam' },
  { crs: 'DNL', name: 'Dunlop' },
  { crs: 'DNO', name: 'Dunrobin Castle' },
  { crs: 'DYC', name: 'Dyce' },
  { crs: 'EKL', name: 'East Kilbride' },
  { crs: 'ELT', name: 'East Linton' },
  { crs: 'EST', name: 'Easterhouse' },
  { crs: 'EGY', name: 'Edinburgh Gateway' },
  { crs: 'EDP', name: 'Edinburgh Park' },
  { crs: 'EDB', name: 'Edinburgh Waverley' },
  { crs: 'ELG', name: 'Elgin' },
  { crs: 'EKB', name: 'Eskbank' },
  { crs: 'EXG', name: 'Exhibition Centre' },
  { crs: 'FRL', name: 'Fairlie' },
  { crs: 'FKG', name: 'Falkirk Grahamston' },
  { crs: 'FKK', name: 'Falkirk High' },
  { crs: 'FOC', name: 'Falls of Cruachan' },
  { crs: 'FLD', name: 'Fauldhouse' },
  { crs: 'FRN', name: 'Fearn' },
  { crs: 'FOR', name: 'Forres' },
  { crs: 'FRS', name: 'Forsinard' },
  { crs: 'FTM', name: 'Fort Matilda' },
  { crs: 'FTW', name: 'Fort William' },
  { crs: 'GAL', name: 'Galashiels' },
  { crs: 'GCH', name: 'Garelochhead' },
  { crs: 'GAR', name: 'Garrowhill' },
  { crs: 'GRS', name: 'Garscadden' },
  { crs: 'GRH', name: 'Gartcosh' },
  { crs: 'GVE', name: 'Garve' },
  { crs: 'GGJ', name: 'Georgemas Junction' },
  { crs: 'GFN', name: 'Giffnock' },
  { crs: 'GSC', name: 'Gilshochill' },
  { crs: 'GIR', name: 'Girvan' },
  { crs: 'GLC', name: 'Glasgow Central' },
  { crs: 'GLQ', name: 'Glasgow Queen Street' },
  { crs: 'GLE', name: 'Gleneagles' },
  { crs: 'GLF', name: 'Glenfinnan' },
  { crs: 'GLG', name: 'Glengarnock' },
  { crs: 'GLT', name: 'Glenrothes with Thornton' },
  { crs: 'GOF', name: 'Golf Street' },
  { crs: 'GOL', name: 'Golspie' },
  { crs: 'GBG', name: 'Gorebridge' },
  { crs: 'GRK', name: 'Gourock' },
  { crs: 'GRL', name: 'Greenfaulds' },
  { crs: 'GKC', name: 'Greenock Central' },
  { crs: 'GKW', name: 'Greenock West' },
  { crs: 'GEA', name: 'Gretna Green' },
  { crs: 'HMY', name: 'Hairmyres' },
  { crs: 'HNC', name: 'Hamilton Central' },
  { crs: 'HNW', name: 'Hamilton West' },
  { crs: 'HTW', name: 'Hartwood' },
  { crs: 'HKH', name: 'Hawkhead' },
  { crs: 'HYM', name: 'Haymarket' },
  { crs: 'HLC', name: 'Helensburgh Central' },
  { crs: 'HLU', name: 'Helensburgh Upper' },
  { crs: 'HMS', name: 'Helmsdale' },
  { crs: 'HST', name: 'High Street' },
  { crs: 'HLF', name: 'Hillfoot' },
  { crs: 'HLE', name: 'Hillington East' },
  { crs: 'HLW', name: 'Hillington West' },
  { crs: 'HLY', name: 'Holytown' },
  { crs: 'HOZ', name: 'Howwood' },
  { crs: 'HNT', name: 'Huntly' },
  { crs: 'HYN', name: 'Hyndland' },
  { crs: 'INS', name: 'Insch' },
  { crs: 'IGD', name: 'Invergordon' },
  { crs: 'ING', name: 'Invergowrie' },
  { crs: 'INK', name: 'Inverkeithing' },
  { crs: 'INP', name: 'Inverkip' },
  { crs: 'INV', name: 'Inverness' },
  { crs: 'IVA', name: 'Inverness Airport' },
  { crs: 'INH', name: 'Invershin' },
  { crs: 'INR', name: 'Inverurie' },
  { crs: 'IRV', name: 'Irvine' },
  { crs: 'JHN', name: 'Johnstone' },
  { crs: 'JOR', name: 'Jordanhill' },
  { crs: 'KEH', name: 'Keith' },
  { crs: 'KVD', name: 'Kelvindale' },
  { crs: 'KNS', name: 'Kennishead' },
  { crs: 'KIL', name: 'Kildonan' },
  { crs: 'KMK', name: 'Kilmarnock' },
  { crs: 'KLM', name: 'Kilmaurs' },
  { crs: 'KPT', name: 'Kilpatrick' },
  { crs: 'KWN', name: 'Kilwinning' },
  { crs: 'KBC', name: 'Kinbrace' },
  { crs: 'KGH', name: 'Kinghorn' },
  { crs: 'KGP', name: 'Kings Park' },
  { crs: 'KGE', name: 'Kingsknowe' },
  { crs: 'KIN', name: 'Kingussie' },
  { crs: 'KTR', name: 'Kintore' },
  { crs: 'KDY', name: 'Kirkcaldy' },
  { crs: 'KRK', name: 'Kirkconnel' },
  { crs: 'KKH', name: 'Kirkhill' },
  { crs: 'KKN', name: 'Kirknewton' },
  { crs: 'KWD', name: 'Kirkwood' },
  { crs: 'KYL', name: 'Kyle of Lochalsh' },
  { crs: 'LDY', name: 'Ladybank' },
  { crs: 'LRG', name: 'Lairg' },
  { crs: 'LNK', name: 'Lanark' },
  { crs: 'LGB', name: 'Langbank' },
  { crs: 'LGS', name: 'Langside' },
  { crs: 'LBT', name: 'Larbert' },
  { crs: 'LAR', name: 'Largs' },
  { crs: 'LRH', name: 'Larkhall' },
  { crs: 'LAU', name: 'Laurencekirk' },
  { crs: 'LNZ', name: 'Lenzie' },
  { crs: 'LEU', name: 'Leuchars' },
  { crs: 'LEV', name: 'Leven' },
  { crs: 'LIN', name: 'Linlithgow' },
  { crs: 'LSN', name: 'Livingston North' },
  { crs: 'LVG', name: 'Livingston South' },
  { crs: 'LHA', name: 'Loch Awe' },
  { crs: 'LHE', name: 'Loch Eil Outward Bound' },
  { crs: 'LCL', name: 'Lochailort' },
  { crs: 'LCS', name: 'Locheilside' },
  { crs: 'LCG', name: 'Lochgelly' },
  { crs: 'LCC', name: 'Lochluichart' },
  { crs: 'LHW', name: 'Lochwinnoch' },
  { crs: 'LOC', name: 'Lockerbie' },
  { crs: 'LND', name: 'Longniddry' },
  { crs: 'MLG', name: 'Mallaig' },
  { crs: 'MNC', name: 'Markinch' },
  { crs: 'MYH', name: 'Maryhill' },
  { crs: 'MAX', name: 'Maxwell Park' },
  { crs: 'MAY', name: 'Maybole' },
  { crs: 'MEY', name: 'Merryton' },
  { crs: 'MIN', name: 'Milliken Park' },
  { crs: 'MLN', name: 'Milngavie' },
  { crs: 'MON', name: 'Monifieth' },
  { crs: 'MTS', name: 'Montrose' },
  { crs: 'MRR', name: 'Morar' },
  { crs: 'MPK', name: 'Mosspark' },
  { crs: 'MTH', name: 'Motherwell' },
  { crs: 'MFL', name: 'Mount Florida' },
  { crs: 'MTV', name: 'Mount Vernon' },
  { crs: 'MOO', name: 'Muir of Ord' },
  { crs: 'MUI', name: 'Muirend' },
  { crs: 'MUB', name: 'Musselburgh' },
  { crs: 'NRN', name: 'Nairn' },
  { crs: 'NEI', name: 'Neilston' },
  { crs: 'NCK', name: 'New Cumnock' },
  { crs: 'NEW', name: 'Newcraighall' },
  { crs: 'NTN', name: 'Newton' },
  { crs: 'NOA', name: 'Newton-On-Ayr' },
  { crs: 'NEG', name: 'Newtongrange' },
  { crs: 'NWR', name: 'Newtonmore' },
  { crs: 'NIT', name: 'Nitshill' },
  { crs: 'NBW', name: 'North Berwick' },
  { crs: 'NQU', name: 'North Queensferry' },
  { crs: 'OBN', name: 'Oban' },
  { crs: 'PCN', name: 'Paisley Canal' },
  { crs: 'PYG', name: 'Paisley Gilmour Street' },
  { crs: 'PYJ', name: 'Paisley St James' },
  { crs: 'PTK', name: 'Partick' },
  { crs: 'PTT', name: 'Patterton' },
  { crs: 'PTH', name: 'Perth' },
  { crs: 'PIT', name: 'Pitlochry' },
  { crs: 'PLK', name: 'Plockton' },
  { crs: 'PWE', name: 'Pollokshaws East' },
  { crs: 'PWW', name: 'Pollokshaws West' },
  { crs: 'PLE', name: 'Pollokshields East' },
  { crs: 'PLW', name: 'Pollokshields West' },
  { crs: 'PMT', name: 'Polmont' },
  { crs: 'PTG', name: 'Port Glasgow' },
  { crs: 'PLN', name: 'Portlethen' },
  { crs: 'PPK', name: 'Possilpark & Parkhouse' },
  { crs: 'PST', name: 'Prestonpans' },
  { crs: 'PRA', name: 'Prestwick International Airport' },
  { crs: 'PTW', name: 'Prestwick Town' },
  { crs: 'PTL', name: 'Priesthill & Darnley' },
  { crs: 'QPK', name: 'Queens Park (Glasgow)' },
  { crs: 'RAN', name: 'Rannoch' },
  { crs: 'RTN', name: 'Renton' },
  { crs: 'RSN', name: 'Reston' },
  { crs: 'RRN', name: 'Robroyston' },
  { crs: 'ROG', name: 'Rogart' },
  { crs: 'ROS', name: 'Rosyth' },
  { crs: 'RYB', name: 'Roy Bridge' },
  { crs: 'RUT', name: 'Rutherglen' },
  { crs: 'SLT', name: 'Saltcoats' },
  { crs: 'SQH', name: 'Sanquhar' },
  { crs: 'SCT', name: 'Scotscalder' },
  { crs: 'SCH', name: 'Scotstounhill' },
  { crs: 'SFI', name: 'Shawfair' },
  { crs: 'SHL', name: 'Shawlands' },
  { crs: 'SLS', name: 'Shettleston' },
  { crs: 'SDM', name: 'Shieldmuir' },
  { crs: 'SHS', name: 'Shotts' },
  { crs: 'SIN', name: 'Singer' },
  { crs: 'SLA', name: 'Slateford' },
  { crs: 'SGL', name: 'South Gyle' },
  { crs: 'SBR', name: 'Spean Bridge' },
  { crs: 'SPR', name: 'Springburn' },
  { crs: 'SPF', name: 'Springfield' },
  { crs: 'SPS', name: 'Stepps' },
  { crs: 'STV', name: 'Stevenston' },
  { crs: 'STT', name: 'Stewarton' },
  { crs: 'STG', name: 'Stirling' },
  { crs: 'STN', name: 'Stonehaven' },
  { crs: 'SOI', name: 'Stow' },
  { crs: 'STR', name: 'Stranraer' },
  { crs: 'STC', name: 'Strathcarron' },
  { crs: 'STF', name: 'Stromeferry' },
  { crs: 'SUM', name: 'Summerston' },
  { crs: 'TAI', name: 'Tain' },
  { crs: 'TAY', name: 'Taynuilt' },
  { crs: 'THB', name: 'Thornliebank' },
  { crs: 'THT', name: 'Thorntonhall' },
  { crs: 'THS', name: 'Thurso' },
  { crs: 'TRN', name: 'Troon' },
  { crs: 'TUL', name: 'Tulloch' },
  { crs: 'TWB', name: 'Tweedbank' },
  { crs: 'TYL', name: 'Tyndrum Lower' },
  { crs: 'UDD', name: 'Uddingston' },
  { crs: 'UHA', name: 'Uphall' },
  { crs: 'UTY', name: 'Upper Tyndrum' },
  { crs: 'WAF', name: 'Wallyford' },
  { crs: 'WMS', name: 'Wemyss Bay' },
  { crs: 'WCL', name: 'West Calder' },
  { crs: 'WKB', name: 'West Kilbride' },
  { crs: 'WTA', name: 'Wester Hailes' },
  { crs: 'WES', name: 'Westerton' },
  { crs: 'WFF', name: 'Whifflet' },
  { crs: 'WNL', name: 'Whinhill' },
  { crs: 'WCR', name: 'Whitecraigs' },
  { crs: 'WCK', name: 'Wick' },
  { crs: 'WLM', name: 'Williamwood' },
  { crs: 'WSH', name: 'Wishaw' },
  { crs: 'WDL', name: 'Woodhall' },
  { crs: 'YOK', name: 'Yoker' },
];
